/* Lesson plans (PowerPoint) per course — generated by tools/build-lesson-plans.py from the owner's decks.
   id = the code teachers see and type in "Unit / page"; file = path in the slides folder. */
/* 5 Oct 2026: EF-B1 is now the full rebuilt course (1A-1 … 10B-2, PE1–PE5, R1-2 … R9-10) with hw, easy (easier homework),
   key and pcm (photocopiables) per lesson, linked to Drive (B1_Green_Course_6B-10B/Unit NN). */
/* 4 Oct 2026: CHEF (rebuilt Kitchen English course) and B1 7A-1/7A-2 were updated by hand: new deck files plus
   hw (homework sheet PDF) and key (teacher answer key PDF). Links appear once the files are uploaded to Drive
   and their IDs added to tools/plan-links.json. */
window.LLS_PLANS = {
 "folder": "https://drive.google.com/drive/folders/1_AyE9xHLZX-tR057npuZEDeoPWiVDOgB",
 "links": {
  "Kitchen_English_Chefs/Chef_L02_Kitchen_equipment.pptx": "https://drive.google.com/file/d/1Wu_KZxK9oigJgx-uNW-YJq_ejwxxyYv5/view",
  "Kitchen_English_Chefs/Chef_L03_Ingredients_and_stock.pptx": "https://drive.google.com/file/d/12KaSioPcoHFBoR7z_OVUvmRNM4XhAAc5/view",
  "Kitchen_English_Chefs/Chef_L04_Kitchen_commands.pptx": "https://drive.google.com/file/d/1aE5QcqPxfRCNiStGYYSkbrKx-DGB_BX2/view",
  "Kitchen_English_Chefs/Chef_L05_Cooking_methods_and_recipes.pptx": "https://drive.google.com/file/d/1NgFKlPKF62-wHm8M2cJaiW2Kiw6xFHcc/view",
  "Kitchen_English_Chefs/Chef_L06_Numbers_quantities_time.pptx": "https://drive.google.com/file/d/1TjiJK8RJD6bpZFOR8wEkiYRvLM8H8bSY/view",
  "Kitchen_English_Chefs/Chef_L07_Health_safety_hygiene.pptx": "https://drive.google.com/file/d/1dXfAckN7ux_XOHSe85Y-QwEAk-Ea9ddI/view",
  "Kitchen_English_Chefs/Chef_L08_Allergens_and_dietary_needs.pptx": "https://drive.google.com/file/d/1_bUzpldpSEOSizoYlqbct6rASbV9WVJF/view",
  "Kitchen_English_Chefs/Chef_L09_Service.pptx": "https://drive.google.com/file/d/1yG075gUt_EB0ml-MQzqJ0OpsP-mUW5fL/view",
  "Kitchen_English_Chefs/Chef_L10_Problems_and_final_shift.pptx": "https://drive.google.com/file/d/14NZnNScLrbFLP9sczdCu3Js3y-2bGdzO/view",
  "Kitchen_English_Chefs/Chef_L01_Homework_sheet.pdf": "https://drive.google.com/file/d/1hIHFSZe69CUGOINxdaO8p7Pkb2OfJMix/view",
  "Kitchen_English_Chefs/Chef_L02_Homework_sheet.pdf": "https://drive.google.com/file/d/1JiE66Fuuea--63E6GPI2lU1wxksf29Bq/view",
  "Kitchen_English_Chefs/Chef_L03_Homework_sheet.pdf": "https://drive.google.com/file/d/1E2QPq3aPLfzb2vuxfBK81qn4_Nr_AyGJ/view",
  "Kitchen_English_Chefs/Chef_L04_Homework_sheet.pdf": "https://drive.google.com/file/d/1df7KGBZEcdzt7D_yna2LPKEQXD_JrsS1/view",
  "Kitchen_English_Chefs/Chef_L05_Homework_sheet.pdf": "https://drive.google.com/file/d/1GkOOVKAqYZ04QCCG0GYWvZDv85me8qRy/view",
  "Kitchen_English_Chefs/Chef_L06_Homework_sheet.pdf": "https://drive.google.com/file/d/14FH4a1-NzVfNiLvgHfIjk_VEqIyhz_rI/view",
  "Kitchen_English_Chefs/Chef_L07_Homework_sheet.pdf": "https://drive.google.com/file/d/1eYpQdEDAbBkJUbx6wItE0ldF_qvQHozJ/view",
  "Kitchen_English_Chefs/Chef_L08_Homework_sheet.pdf": "https://drive.google.com/file/d/1YYZwr_uagKkW_Or-jr3y-38kkps2nnXn/view",
  "Kitchen_English_Chefs/Chef_L09_Homework_sheet.pdf": "https://drive.google.com/file/d/1z8ExZm0pSL-0Fe2PfuMSUgIQjkfsQFn2/view",
  "Kitchen_English_Chefs/Chef_L10_Homework_sheet.pdf": "https://drive.google.com/file/d/1ulQAxBAsVtTHiazSkAa3Dv0PJJ63RpbM/view",
  "Kitchen_English_Chefs/Chef_L01_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1qb70cI-Lu6z5tIpjatgCEDG2_3ZJIrMp/view",
  "Kitchen_English_Chefs/Chef_L02_Teacher_answer_key.pdf": "https://drive.google.com/file/d/19n9GDFbSR9-6OC8pV8e56fTkeJ9ELpn5/view",
  "Kitchen_English_Chefs/Chef_L03_Teacher_answer_key.pdf": "https://drive.google.com/file/d/15OW6n4iJy9s6J9zBFSX6-5qj-2PYFtYV/view",
  "Kitchen_English_Chefs/Chef_L04_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1WnU9AIcdipPKSV7ZiSSbdjce_Ta5Ucdp/view",
  "Kitchen_English_Chefs/Chef_L05_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1rxyD_8iHJc6wJV6Qrnek_iu_MvIsV3w1/view",
  "Kitchen_English_Chefs/Chef_L06_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1eBmgTwzuroia0sm1XoF3uBXEvdVpSbVK/view",
  "Kitchen_English_Chefs/Chef_L07_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1ZC0ONxS-dmjBtRf_O8h3wj_kXY-Hp46_/view",
  "Kitchen_English_Chefs/Chef_L08_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1ZKS_FUpf3edz9puW3pOvz7T4Y8AG-AVF/view",
  "Kitchen_English_Chefs/Chef_L09_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1WgDAuotHFAE5Hb28udDlRl6hRqXQPBGx/view",
  "Kitchen_English_Chefs/Chef_L10_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1Qp4yxsqshoeerGMk9c6GDlqGkYChWeA8/view",
  "B1_Green_Course_6B-10B/B1_1A-1_Eating_in_and_out.pptx": "https://drive.google.com/file/d/18bNBgSrmuDZBehdepE7oTSPwjDm44kLA/view",
  "B1_Green_Course_6B-10B/B1_1A-1_Homework_sheet.pdf": "https://drive.google.com/file/d/1X2PTUr1GZPrNS0oJuTAtVnxE-r-JNeHu/view",
  "B1_Green_Course_6B-10B/B1_1A-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1PRMOezsM7hnBzmclWlzxC0uuSgMgNWEh/view",
  "B1_Green_Course_6B-10B/B1_1A-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1ZamtDxpX-JiIA24abKwBR6PuYyfOBdIU/view",
  "B1_Green_Course_6B-10B/B1_1A_Photocopiables.pdf": "https://drive.google.com/file/d/1cb5uwcXxS8ztoKHtsOnWunnyGfvO1ArN/view",
  "B1_Green_Course_6B-10B/B1_1A-2_Eating_in_and_out.pptx": "https://drive.google.com/file/d/1FPBAYq9FE1e_Ll4wmtPpL9UtVQbVoCCy/view",
  "B1_Green_Course_6B-10B/B1_1A-2_Homework_sheet.pdf": "https://drive.google.com/file/d/1wLON1hYOslHo9lX26IVjxu10WPVfrehU/view",
  "B1_Green_Course_6B-10B/B1_1A-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1hPOL8sVl5fq4QNiS2QDIMHCbN8gih4rY/view",
  "B1_Green_Course_6B-10B/B1_1A-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1myipdsRFNq8-unrz05kmKNVztEs0C6pM/view",
  "B1_Green_Course_6B-10B/B1_1B-1_Modern_families.pptx": "https://drive.google.com/file/d/1mjNGde3fh680fiytiv-yuWFO0bnkF0c7/view",
  "B1_Green_Course_6B-10B/B1_1B-1_Homework_sheet.pdf": "https://drive.google.com/file/d/11O8HaDvGZuSIOEWvhCHh6EbZRwe3oo1S/view",
  "B1_Green_Course_6B-10B/B1_1B-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1kBW-CwFupKsGOhUf9BqlVC8Ah2d3jElY/view",
  "B1_Green_Course_6B-10B/B1_1B-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1xi75sUk9wT54gxzNAeQOOv2zuGkVnyzW/view",
  "B1_Green_Course_6B-10B/B1_1B_Photocopiables.pdf": "https://drive.google.com/file/d/1PWwQNxokJR4De2t5O2-GkebU9wQMZegV/view",
  "B1_Green_Course_6B-10B/B1_1B-2_Modern_families.pptx": "https://drive.google.com/file/d/1AvDWq2rSmtSOTpiXlJZsqG5H7qLr4VIU/view",
  "B1_Green_Course_6B-10B/B1_1B-2_Homework_sheet.pdf": "https://drive.google.com/file/d/1g4LozelRIVSlULNM3VFtUlreeAj-hehJ/view",
  "B1_Green_Course_6B-10B/B1_1B-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1mxqKCDjj5Llk4uDNYjxDE2dDv03BoSvZ/view",
  "B1_Green_Course_6B-10B/B1_1B-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1AHJkZfdL7Hjbx1nV7eH9wlYsV3L3XWRv/view",
  "B1_Green_Course_6B-10B/B1_PE1_Meeting_the_parents.pptx": "https://drive.google.com/file/d/1g13e_v6mo-1SxTK-Wvw5Ip4tR8jMpP8p/view",
  "B1_Green_Course_6B-10B/B1_PE1_Homework_sheet.pdf": "https://drive.google.com/file/d/1NXgYSg72dXHocTamqK72Q73kq1Rnc1eV/view",
  "B1_Green_Course_6B-10B/B1_PE1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1fVJacuOnREk7bMWYLRruYPhaIBorQXGZ/view",
  "B1_Green_Course_6B-10B/B1_PE1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1Wkq3HvZ8Y9qb0Au5I6c8ncD63iERpTfl/view",
  "B1_Green_Course_6B-10B/B1_2A-1_Spending_money.pptx": "https://drive.google.com/file/d/1nhEsTGC8kDUe2UkSiLlCNMx9f4wlTJT3/view",
  "B1_Green_Course_6B-10B/B1_2A-1_Homework_sheet.pdf": "https://drive.google.com/file/d/1WIw9PsBZWVklbEtNRHApuKNPFMD_2EzT/view",
  "B1_Green_Course_6B-10B/B1_2A-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1rwjijp3cXxLkVu10SKk7QPBHQXsL4qGk/view",
  "B1_Green_Course_6B-10B/B1_2A-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/17U7WBZLiOjUnXAY-Cz4uByUMQmKmfdO6/view",
  "B1_Green_Course_6B-10B/B1_2A_Photocopiables.pdf": "https://drive.google.com/file/d/16rRGIov-HF-Nx2vdnfyiAegpqVJ699cV/view",
  "B1_Green_Course_6B-10B/B1_2A-2_Spending_money.pptx": "https://drive.google.com/file/d/1GfosEioA_M6MVEw4UZPjqDSRYqz-MLBc/view",
  "B1_Green_Course_6B-10B/B1_2A-2_Homework_sheet.pdf": "https://drive.google.com/file/d/17hcSXKTd97ppIFvTFzTHFnBHvtPehbKJ/view",
  "B1_Green_Course_6B-10B/B1_2A-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1YkSfHG-HS0ef0pJYNX4ohGv0GATm1mrH/view",
  "B1_Green_Course_6B-10B/B1_2A-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1c6Xno4I9EQ93nOH-S0K-9OuWgNHBPkPk/view",
  "B1_Green_Course_6B-10B/B1_2B-1_Changing_lives.pptx": "https://drive.google.com/file/d/1CYyVJk2tYrdKOIjSKhcXX9mZ9nxwwaQH/view",
  "B1_Green_Course_6B-10B/B1_2B-1_Homework_sheet.pdf": "https://drive.google.com/file/d/1rHtn-ASBkeaQAJjHeGH9EisEO96w2CiI/view",
  "B1_Green_Course_6B-10B/B1_2B-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1wuqykL6EJhPcq63vRojMOBG8AxAUZ_Cx/view",
  "B1_Green_Course_6B-10B/B1_2B-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1zmZnyZL_eSRYIse1UqDI8st4iCpGCPTG/view",
  "B1_Green_Course_6B-10B/B1_2B_Photocopiables.pdf": "https://drive.google.com/file/d/1QJZdQcmavluEWtfLX2JIB_TB9V3jqWHk/view",
  "B1_Green_Course_6B-10B/B1_2B-2_Changing_lives.pptx": "https://drive.google.com/file/d/1LXDoWx9gDlhf1O09Vv1OF82sRmEuphMZ/view",
  "B1_Green_Course_6B-10B/B1_2B-2_Homework_sheet.pdf": "https://drive.google.com/file/d/1nD5OmFUAuimj-hgORHU6miKsgajpc9wl/view",
  "B1_Green_Course_6B-10B/B1_2B-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1ymy6w1kGN24TI69bEAFeOkMeRrYvPNRa/view",
  "B1_Green_Course_6B-10B/B1_2B-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1Ise0n6IlgZLFsjv-0HDdjP18yBy4v1_t/view",
  "B1_Green_Course_6B-10B/B1_R1-2_Revise_and_Check_1-2.pptx": "https://drive.google.com/file/d/1w9kUoG_v9ZnM3QkZlf-iX2CnHF4zhSpR/view",
  "B1_Green_Course_6B-10B/B1_R1-2_Homework_sheet.pdf": "https://drive.google.com/file/d/1BNUTG3Y7-va51fJmq_oXIp-0Ujh8HU-s/view",
  "B1_Green_Course_6B-10B/B1_R1-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1L8ZEyblBWkFxUplWIfvhHlhdFicI18o1/view",
  "B1_Green_Course_6B-10B/B1_R1-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1FCHVfSU49IQ4-RAbHyz0213Q8g4ara5X/view",
  "B1_Green_Course_6B-10B/B1_3A-1_Survive_the_drive.pptx": "https://drive.google.com/file/d/1iepKPFIGvpD_MCvxtjwm_aowt2S0rShs/view",
  "B1_Green_Course_6B-10B/B1_3A-1_Homework_sheet.pdf": "https://drive.google.com/file/d/1ttRGB92OJHZU-63J8Rl5-ae1op2UbhFm/view",
  "B1_Green_Course_6B-10B/B1_3A-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1WS_ENXGSc8nfvyi-riPH6quuQYl6KA3S/view",
  "B1_Green_Course_6B-10B/B1_3A-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1gkr2-W95xm1xjcn39aKYOwOpY4y0ymPW/view",
  "B1_Green_Course_6B-10B/B1_3A_Photocopiables.pdf": "https://drive.google.com/file/d/1pfzczJXIt6TF5_jBuSwqO74IjolGP0O5/view",
  "B1_Green_Course_6B-10B/B1_3A-2_Survive_the_drive.pptx": "https://drive.google.com/file/d/1-O8R1NI_tibjZP4AEVl6Ijpu5odsFz4D/view",
  "B1_Green_Course_6B-10B/B1_3A-2_Homework_sheet.pdf": "https://drive.google.com/file/d/1Ku428FyXqNNXXsl3X5GbZUNqnBBvx7PK/view",
  "B1_Green_Course_6B-10B/B1_3A-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1dXFgpqYMEYX4TogahgqrlS1v55iqly44/view",
  "B1_Green_Course_6B-10B/B1_3A-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1sAULegfwgquMz8QXfcjDlKs1HcSr5rUk/view",
  "B1_Green_Course_6B-10B/B1_3B-1_Men_women_and_children.pptx": "https://drive.google.com/file/d/1dM7GdL-rh_L3bAs2z2ox6um0K2Xoi4k4/view",
  "B1_Green_Course_6B-10B/B1_3B-1_Homework_sheet.pdf": "https://drive.google.com/file/d/1HhamhLGoZUdvqqSK3CDzwKIS2Z089VKb/view",
  "B1_Green_Course_6B-10B/B1_3B-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1iaMBGxMd7WYIYCKr_eieSa8gSFEo3nPt/view",
  "B1_Green_Course_6B-10B/B1_3B-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/10PK2JvOfxjYVFpM82Jsk8SyHDUyGoA00/view",
  "B1_Green_Course_6B-10B/B1_3B_Photocopiables.pdf": "https://drive.google.com/file/d/1Q198LSriwfIS95SjDDSQFeidLbae2CDM/view",
  "B1_Green_Course_6B-10B/B1_3B-2_Men_women_and_children.pptx": "https://drive.google.com/file/d/1O5daeXB9vLGtFeRRHQtCszE23RioPB2w/view",
  "B1_Green_Course_6B-10B/B1_3B-2_Homework_sheet.pdf": "https://drive.google.com/file/d/1-LxHoP3poy6Idfpnwn2GfI3DRnzoFJZV/view",
  "B1_Green_Course_6B-10B/B1_3B-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1KSG56gTEau2I5U0lIRRMwHrS8iDTkL95/view",
  "B1_Green_Course_6B-10B/B1_3B-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/14fU9qfdbgFl72C5EvTOTOXXW6MxhOHJy/view",
  "B1_Green_Course_6B-10B/B1_PE2_A_difficult_celebrity.pptx": "https://drive.google.com/file/d/1SNqZB-QvJewTDIjkB_ltK97LjcMMLatK/view",
  "B1_Green_Course_6B-10B/B1_PE2_Homework_sheet.pdf": "https://drive.google.com/file/d/1VYVrcsgpiOQdBx1yOLIosorcLoUhGjI0/view",
  "B1_Green_Course_6B-10B/B1_PE2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1G5K9jiveeM3hiXEfgNE9ADbrFtVUatcT/view",
  "B1_Green_Course_6B-10B/B1_PE2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1VcNca4Sc16eFn_cjWZwBmJcjbfTuV_k3/view",
  "B1_Green_Course_6B-10B/B1_4A-1_Bad_manners.pptx": "https://drive.google.com/file/d/1YXADeAypnhMGvOozjmxbaOV2yIGWa8Z8/view",
  "B1_Green_Course_6B-10B/B1_4A-1_Homework_sheet.pdf": "https://drive.google.com/file/d/1ppHVdqQuE_wFkHTKKWgGf2_tg75T2_e-/view",
  "B1_Green_Course_6B-10B/B1_4A-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1mb4c8oyzEVC3NlO1zQydAq2gqcqZB03l/view",
  "B1_Green_Course_6B-10B/B1_4A-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1G3Odlg6k_qS3QdrwJ_HLv6qlgnQFHKYl/view",
  "B1_Green_Course_6B-10B/B1_4A_Photocopiables.pdf": "https://drive.google.com/file/d/1LW8VtrMS2UoVZZW-w2dt395GX0bArC3Z/view",
  "B1_Green_Course_6B-10B/B1_4A-2_Homework_sheet.pdf": "https://drive.google.com/file/d/1b_IumdQPf0tQXi-91jza0YEvuh8y2GO6/view",
  "B1_Green_Course_6B-10B/B1_4A-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1LfYKjbC6WL7rNKmUDG4O2cUHSY5vRO8N/view",
  "B1_Green_Course_6B-10B/B1_4A-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1mgmaWDrcxw-laH1Y4rDLKWKgb8CCrM-8/view",
  "B1_Green_Course_6B-10B/B1_4B-1_Yes_I_can.pptx": "https://drive.google.com/file/d/1-paclcTxiUoYf6Rx-hGRpjDUVoKAAp0s/view",
  "B1_Green_Course_6B-10B/B1_4B-1_Homework_sheet.pdf": "https://drive.google.com/file/d/12KPlokNOuLCqNkRo8CWRiWeUWrs9aSJH/view",
  "B1_Green_Course_6B-10B/B1_4B-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1TFihqFCexCEIbw-6vKYkZkhPCr4T5Jce/view",
  "B1_Green_Course_6B-10B/B1_4B-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1Uh-997wXweCj28LRkJKYlvybZVZDHHlG/view",
  "B1_Green_Course_6B-10B/B1_4B_Photocopiables.pdf": "https://drive.google.com/file/d/1xKZz6nMQ5sJmT8FY0JuUdSl9LOh0tGpm/view",
  "B1_Green_Course_6B-10B/B1_4B-2_Yes_I_can.pptx": "https://drive.google.com/file/d/19FWZckCCG5uB2C_qBp4a2ANDYOesbmRZ/view",
  "B1_Green_Course_6B-10B/B1_4B-2_Homework_sheet.pdf": "https://drive.google.com/file/d/1j_-1wu2xMelJSzGAyDn5J0yRUgJzbaaf/view",
  "B1_Green_Course_6B-10B/B1_4B-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1ADOoprfTMeFZ91Wk4zjaZWNSa_QSlCsQ/view",
  "B1_Green_Course_6B-10B/B1_4B-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1PkBpaC2kDu1pqkrw5LKUle-oFpf5GmVF/view",
  "B1_Green_Course_6B-10B/B1_R3-4_Homework_sheet.pdf": "https://drive.google.com/file/d/1CraTRbUO225oNLaASbY2qUxd3dM_OAMf/view",
  "B1_Green_Course_6B-10B/B1_R3-4_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1FzNucaKHVTQxeIItzXmme9bK1l7Lc9vo/view",
  "B1_Green_Course_6B-10B/B1_R3-4_Teacher_answer_key.pdf": "https://drive.google.com/file/d/16pgHGLBvo5IcoFMpq-vmX4DhcMiucl80/view",
  "B1_Green_Course_6B-10B/B1_5A-1_Homework_sheet.pdf": "https://drive.google.com/file/d/14EC5E03NIVSlJG-bB2mXsyKtQS4i1AnY/view",
  "B1_Green_Course_6B-10B/B1_5A-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/175N3Qb1WtxgdEqvvh_7WKZqZjC7sLVcD/view",
  "B1_Green_Course_6B-10B/B1_5A-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1PsL1BH5_Zh-nPBzaX8vAJwBdMPxZT_M5/view",
  "B1_Green_Course_6B-10B/B1_5A_Photocopiables.pdf": "https://drive.google.com/file/d/1-oV9W1XIt8imdmw3O9ZeWT3PM5trBTs_/view",
  "B1_Green_Course_6B-10B/B1_5A-2_Sporting_superstitions.pptx": "https://drive.google.com/file/d/1CBU2OO8bvVnPvOX3Z5tbl9NYF_kufDSG/view",
  "B1_Green_Course_6B-10B/B1_5A-2_Homework_sheet.pdf": "https://drive.google.com/file/d/1UAonKtt9Bu0ALQrsCrCPWrAAvnaSEBmL/view",
  "B1_Green_Course_6B-10B/B1_5A-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1I1byHxEStr2568pji9NBajMu-bWvnlnE/view",
  "B1_Green_Course_6B-10B/B1_5A-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1eHFXEon5kaXP3VzsT8Id_68blV1IPWFz/view",
  "B1_Green_Course_6B-10B/B1_5B-1_thewaywemet.pptx": "https://drive.google.com/file/d/1G3mdjx4OjyReXfK3_s-nPx_RStE8sKiG/view",
  "B1_Green_Course_6B-10B/B1_5B-1_Homework_sheet.pdf": "https://drive.google.com/file/d/1BCXK0Pfv8dEvpGOY9eS2vLzodST_BIMV/view",
  "B1_Green_Course_6B-10B/B1_5B-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1ygaxg725Ko0Dzeyd4ftxvcQ-t2PEZqsY/view",
  "B1_Green_Course_6B-10B/B1_5B-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/17ioHUFM1qas1jgFxLcK6U2RPtz-EEMB0/view",
  "B1_Green_Course_6B-10B/B1_5B_Photocopiables.pdf": "https://drive.google.com/file/d/1zsnpWV1J7tO_ZsFZqp7ZVWBTdhMex_2D/view",
  "B1_Green_Course_6B-10B/B1_5B-2_thewaywemet.pptx": "https://drive.google.com/file/d/1hODf7iWh1IEMe6V96CTTdLAdjbXcFedM/view",
  "B1_Green_Course_6B-10B/B1_5B-2_Homework_sheet.pdf": "https://drive.google.com/file/d/1KBSXl_iMpAwArhYkPgBPxzWUv7j0Kb6T/view",
  "B1_Green_Course_6B-10B/B1_5B-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1SLBdL3m21_n3gKCFsJWB1CNwL2oeBAqy/view",
  "B1_Green_Course_6B-10B/B1_5B-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1zL9WmzD6bAqfni7PA0_AdidMiIZpfUt3/view",
  "B1_Green_Course_6B-10B/B1_PE3_Old_friends.pptx": "https://drive.google.com/file/d/1byCYhlyWVnSVQqcFt8Akgr1PhHT033Fd/view",
  "B1_Green_Course_6B-10B/B1_PE3_Homework_sheet.pdf": "https://drive.google.com/file/d/1fSut89bdKfwTutUUbhwaQuKR2hgMA_ws/view",
  "B1_Green_Course_6B-10B/B1_PE3_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1d4e-QGrT0QP9CczJ_gks8eQ2KD-mo-Yj/view",
  "B1_Green_Course_6B-10B/B1_PE3_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1sC-CI0Dl1I2GC_am1apHATn-tP783CKB/view",
  "B1_Green_Course_6B-10B/B1_6A-1_Homework_sheet.pdf": "https://drive.google.com/file/d/1oDL7DSOx-6jDTgijI8-8feOGyY2RgMGT/view",
  "B1_Green_Course_6B-10B/B1_6A-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1YJiOWw13t0FO4zwBqBFe2YB7_EaRB377/view",
  "B1_Green_Course_6B-10B/B1_6A-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1GGUsEupZne_EipBq4bbRHWEM0jrIBN4p/view",
  "B1_Green_Course_6B-10B/B1_6A_Photocopiables.pdf": "https://drive.google.com/file/d/1QtXdE5NxZogOdoVakiyWQLNcoHZyUh05/view",
  "B1_Green_Course_6B-10B/B1_6A-2_Behind_the_scenes.pptx": "https://drive.google.com/file/d/1yabEMSRCrztT0FtQpzudcKuaOcdZpDiv/view",
  "B1_Green_Course_6B-10B/B1_6A-2_Homework_sheet.pdf": "https://drive.google.com/file/d/1afnVg9POWdWPkZuwMbe7PttbFuII-RvE/view",
  "B1_Green_Course_6B-10B/B1_6A-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/16nZknKW-UjO81dTeyccgRORhtcmEZMhm/view",
  "B1_Green_Course_6B-10B/B1_6A-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1lIJWjHBpiVux9ddJpt7rq58ZdB0rN4Iq/view",
  "B1_Green_Course_6B-10B/B1_6B-1_Every_picture_tells_a_story.pptx": "https://drive.google.com/file/d/1DruSZYEOBtHDO2z--YabSHf5yMN57y4M/view",
  "B1_Green_Course_6B-10B/B1_6B-1_Homework_sheet.pdf": "https://drive.google.com/file/d/1QC4TbqNe3vq8qyAPTQg0Ao2ac69ei50d/view",
  "B1_Green_Course_6B-10B/B1_6B-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1mPBsqY65djzuxj2tU28q3DErFjgR-wUD/view",
  "B1_Green_Course_6B-10B/B1_6B-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1exygPgdd7C1RSIEBmX5FD4s3htaJZLLx/view",
  "B1_Green_Course_6B-10B/B1_6B_Photocopiables.pdf": "https://drive.google.com/file/d/1ykA0Ujqe-c6qomYt2TUOEU35bb8xr0kH/view",
  "B1_Green_Course_6B-10B/B1_6B-2_Every_picture_tells_a_story.pptx": "https://drive.google.com/file/d/1BMjdbMrNh-bRtjI9QlS9n4bzwOyXPdLb/view",
  "B1_Green_Course_6B-10B/B1_6B-2_Homework_sheet.pdf": "https://drive.google.com/file/d/1l7h7ecbIZ3VCftOar44iC4HVOfP4Mfal/view",
  "B1_Green_Course_6B-10B/B1_6B-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1kQwDmPoogkyPjRoOtvaw2XJTxy39o5Vv/view",
  "B1_Green_Course_6B-10B/B1_6B-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1NPYz1DEeLyfhnbtqOXk0eudpEG1lgIAB/view",
  "B1_Green_Course_6B-10B/B1_R5-6_Revise_and_Check_5_6.pptx": "https://drive.google.com/file/d/1LvAYdqtFMuHbhkScDXq7JvAUl4wVBu7q/view",
  "B1_Green_Course_6B-10B/B1_R5-6_Homework_sheet.pdf": "https://drive.google.com/file/d/18g0ihq8uLFq0AoqYxY7RGEqo5dj89Pu6/view",
  "B1_Green_Course_6B-10B/B1_R5-6_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/162Nq381erYZ8H4V_oeYWaET0SUi636hs/view",
  "B1_Green_Course_6B-10B/B1_R5-6_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1QJ49fPlSPSZgzsRxTUaqvF_XLjsaL3ck/view",
  "B1_Green_Course_6B-10B/B1_7A-1_Live_and_learn.pptx": "https://drive.google.com/file/d/1UrGorBbeYYZ2EnMVJ-RpXkynehJB-imK/view",
  "B1_Green_Course_6B-10B/B1_7A-1_Homework_sheet.pdf": "https://drive.google.com/file/d/1ATh8VBeERrkrztQTZfWEn6Fg8Y_y0aO7/view",
  "B1_Green_Course_6B-10B/B1_7A-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1t9x9LFxIzvHE5tY7W72MjKPKTZ69-LAY/view",
  "B1_Green_Course_6B-10B/B1_7A-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1pzFs7MFOMnvYyQZ4Rzq_jYwk74UnIIZl/view",
  "B1_Green_Course_6B-10B/B1_7A_Photocopiables.pdf": "https://drive.google.com/file/d/1IeY4XQyd5j9rE_2iRPZllh6PjafDo4HF/view",
  "B1_Green_Course_6B-10B/B1_7A-2_Live_and_learn.pptx": "https://drive.google.com/file/d/1frmWMWdcJjNSnB9X0BGN7N20yjx0mmqA/view",
  "B1_Green_Course_6B-10B/B1_7A-2_Homework_sheet.pdf": "https://drive.google.com/file/d/1TncUbkQxDIHDuStzG0ELH9hXIqX5ysRH/view",
  "B1_Green_Course_6B-10B/B1_7A-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1Qf-275nZEfCkF68bGjeJN99BKY5mQfB-/view",
  "B1_Green_Course_6B-10B/B1_7A-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1kZbD3Apk2IUUV1sJHfJc3gx7-ZO8qYnE/view",
  "B1_Green_Course_6B-10B/B1_7B-1_The_hotel_of_Mum_and_Dad.pptx": "https://drive.google.com/file/d/1V6euqXamNJsszmK5e9oJ-Mmd-b0BGGUW/view",
  "B1_Green_Course_6B-10B/B1_7B-1_Homework_sheet.pdf": "https://drive.google.com/file/d/1hXmUDvhOBUVp9QWC7NTfbLS7jugGz1XB/view",
  "B1_Green_Course_6B-10B/B1_7B-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1R6KRYYXqlWqLoaBUtrw8Ec-tG_8Mxuuc/view",
  "B1_Green_Course_6B-10B/B1_7B-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1Bdp1LUQX7HuwLgC73IX-Dbjou3mvnrR1/view",
  "B1_Green_Course_6B-10B/B1_7B_Photocopiables.pdf": "https://drive.google.com/file/d/18HZA1eh6sEKVLZGraQoGnoq-sa_6HSF_/view",
  "B1_Green_Course_6B-10B/B1_7B-2_The_hotel_of_Mum_and_Dad.pptx": "https://drive.google.com/file/d/1yLLsOuq283-eszk-0ggXtRSlI333VRdc/view",
  "B1_Green_Course_6B-10B/B1_7B-2_Homework_sheet.pdf": "https://drive.google.com/file/d/10UaSWz0vXbs-Fq-cT6MwsRKwxDDUOhAa/view",
  "B1_Green_Course_6B-10B/B1_7B-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1-coDHB08vJBz8KI8n8NKnn34jwG5t92f/view",
  "B1_Green_Course_6B-10B/B1_7B-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1_omm9CtkbBdXVf7q5lLr2hZojH0LNC_M/view",
  "B1_Green_Course_6B-10B/B1_PE4_Boys_night_out.pptx": "https://drive.google.com/file/d/16dkneJ1qzeSHozzYrp16ggF5Ksqof3as/view",
  "B1_Green_Course_6B-10B/B1_PE4_Homework_sheet.pdf": "https://drive.google.com/file/d/1GLIxD0opLpVvJKbnGLDnZEIsAVrPvuf3/view",
  "B1_Green_Course_6B-10B/B1_PE4_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1EeTa8ZhrkRufzlkmX4JooD4P6e9WrxqE/view",
  "B1_Green_Course_6B-10B/B1_PE4_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1JdgXzCA3nv76zk_17_15uvvTYlwFGQ8p/view",
  "B1_Green_Course_6B-10B/B1_8A-1_The_right_job_for_you.pptx": "https://drive.google.com/file/d/1UIl4cWkzy9Ii6pY1tooxpC_eNYQjxGcE/view",
  "B1_Green_Course_6B-10B/B1_8A-1_Homework_sheet.pdf": "https://drive.google.com/file/d/1P8P0vRs4IsyuwQ3BwUzch_oU5wyEpVp5/view",
  "B1_Green_Course_6B-10B/B1_8A-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/12YmBZa8bywNQfxc0Mphy0XUEfzNARbf-/view",
  "B1_Green_Course_6B-10B/B1_8A-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/10iVT1viaBi6yyT1qU8pZhPvGy3nhn7xb/view",
  "B1_Green_Course_6B-10B/B1_8A_Photocopiables.pdf": "https://drive.google.com/file/d/1u5ehVjtQ9x62fys9w19_mnQDX7phW-Tn/view",
  "B1_Green_Course_6B-10B/B1_8A-2_The_right_job_for_you.pptx": "https://drive.google.com/file/d/1rZSiKNqr2OALSrKNlEnXNPhKTpK8yQjK/view",
  "B1_Green_Course_6B-10B/B1_8A-2_Homework_sheet.pdf": "https://drive.google.com/file/d/16UHZeHFHAheXkJeZ3wjVMAei7meAdAfE/view",
  "B1_Green_Course_6B-10B/B1_8A-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1i00OS9M9_CfDtPbgI4wyT_LcHfCM7dSJ/view",
  "B1_Green_Course_6B-10B/B1_8A-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1IXbx-4um5UH9MHHBWtnxPvwXUgV11q1x/view",
  "B1_Green_Course_6B-10B/B1_8B-1_Have_a_nice_day.pptx": "https://drive.google.com/file/d/1-pbj-T5ZxNVwYSU8I28-81ubNGQRjWBl/view",
  "B1_Green_Course_6B-10B/B1_8B-1_Homework_sheet.pdf": "https://drive.google.com/file/d/1K08CSDwFxNMWsIL9CInEngYHTUAAU7ir/view",
  "B1_Green_Course_6B-10B/B1_8B-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1qdU2dwWh-DoX_wwBfsqltNAq3vBS9aa_/view",
  "B1_Green_Course_6B-10B/B1_8B-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1IhTpnCMC4GujNabukf8RVYYlHH83txpU/view",
  "B1_Green_Course_6B-10B/B1_8B_Photocopiables.pdf": "https://drive.google.com/file/d/16rUxbhkQYpWX_948MuXGMzPaCi0blzQc/view",
  "B1_Green_Course_6B-10B/B1_8B-2_Have_a_nice_day.pptx": "https://drive.google.com/file/d/1UAcRZn5uqrP41vk06xkFgr0CW6AjkI-9/view",
  "B1_Green_Course_6B-10B/B1_8B-2_Homework_sheet.pdf": "https://drive.google.com/file/d/1nV3OjAbKZ5yu4bjbczxUYsBjMYavEAme/view",
  "B1_Green_Course_6B-10B/B1_8B-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1tIT_hLef8VjY6jMnUA7i6HxYQbizTq2h/view",
  "B1_Green_Course_6B-10B/B1_8B-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1Ds7T3Ycod746QATxAri9Kn4rb91E0uva/view",
  "B1_Green_Course_6B-10B/B1_R7-8_Revise_and_Check_7_8.pptx": "https://drive.google.com/file/d/1OuKsGnVYvwPIeDNL8ZOajhl-stfXrAex/view",
  "B1_Green_Course_6B-10B/B1_R7-8_Homework_sheet.pdf": "https://drive.google.com/file/d/1Uxi-7o-dMN4U3aG-Z7kq3JmpA8ITOtdo/view",
  "B1_Green_Course_6B-10B/B1_R7-8_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1cyV1d9s6leHAd1Fvmd5LJOSECIkjNXlX/view",
  "B1_Green_Course_6B-10B/B1_R7-8_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1G_5M30MPJOSvXgXfjYmzUSQ-b0N8snQX/view",
  "B1_Green_Course_6B-10B/B1_9A-1_Lucky_encounters.pptx": "https://drive.google.com/file/d/1jnI0nxh5NelxJqo3MtAk5ATwEvfYkiql/view",
  "B1_Green_Course_6B-10B/B1_9A-1_Homework_sheet.pdf": "https://drive.google.com/file/d/17ct_phzbTIUy5wkXN6LzGInMX2fFJguW/view",
  "B1_Green_Course_6B-10B/B1_9A-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1SOc7Do9BhR9804arKGaNxVMpbdyuBhPz/view",
  "B1_Green_Course_6B-10B/B1_9A-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1Pfxs61p13kEy2XzeBFFqq-Kd95lBAtxO/view",
  "B1_Green_Course_6B-10B/B1_9A_Photocopiables.pdf": "https://drive.google.com/file/d/1qZM_YVvRvcK503DktZ20MYPQ4Vrneeo9/view",
  "B1_Green_Course_6B-10B/B1_9A-2_Lucky_encounters.pptx": "https://drive.google.com/file/d/1ywdfojf692OdmKor515-cVEUilJMtug5/view",
  "B1_Green_Course_6B-10B/B1_9A-2_Homework_sheet.pdf": "https://drive.google.com/file/d/1F1Bm5Rj0_5ZAIrVp28uIBqqPAjYjSjxV/view",
  "B1_Green_Course_6B-10B/B1_9A-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/111KWy6VIyHsfPGVXfS-OoxhJZ0cOppxy/view",
  "B1_Green_Course_6B-10B/B1_9A-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1WFWqeobCet2QUQhsiRNNCqHbfftCj8aT/view",
  "B1_Green_Course_6B-10B/B1_9B-1_Digital_detox.pptx": "https://drive.google.com/file/d/1Tkv5y268auHhSKV4Rih_mxOXcRZp27u8/view",
  "B1_Green_Course_6B-10B/B1_9B-1_Homework_sheet.pdf": "https://drive.google.com/file/d/1CYVpcWI1ImGSPrELQrLW41A573Z97_3Z/view",
  "B1_Green_Course_6B-10B/B1_9B-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1JEtLNImisULtZ8SUYw9BVMhgoBf8O7Ei/view",
  "B1_Green_Course_6B-10B/B1_9B-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/18dqAA546kA_nfEkVj409h6k4w65drC-f/view",
  "B1_Green_Course_6B-10B/B1_9B_Photocopiables.pdf": "https://drive.google.com/file/d/1hVjw6xip07mJFbbqoBSndQOYXXVsgpWJ/view",
  "B1_Green_Course_6B-10B/B1_9B-2_Digital_detox.pptx": "https://drive.google.com/file/d/1rfa005PtMdLu4azgswgHvovo9X3Zz_66/view",
  "B1_Green_Course_6B-10B/B1_9B-2_Homework_sheet.pdf": "https://drive.google.com/file/d/1PuXLBF70mq5LbbBvPa12vguaH8sLjPNp/view",
  "B1_Green_Course_6B-10B/B1_9B-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1FaoZuYlc8UIGz3Wd0zZEZKqFcTgqsMvJ/view",
  "B1_Green_Course_6B-10B/B1_9B-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1VcmdN2FG3UMYlHajHH3OCoTO5MKXm56-/view",
  "B1_Green_Course_6B-10B/B1_PE5_Unexpected_events.pptx": "https://drive.google.com/file/d/1g-CrAv0h70sO-VWkDduYdMUvBkJJeXQR/view",
  "B1_Green_Course_6B-10B/B1_PE5_Homework_sheet.pdf": "https://drive.google.com/file/d/1qT-50Ur3Dgi_Fk4sG8tq5u3TY5OHyGhh/view",
  "B1_Green_Course_6B-10B/B1_PE5_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1AX9qqUpdo3nzjRO2k-Rrm4oUDAp9NPSS/view",
  "B1_Green_Course_6B-10B/B1_PE5_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1pPpCFDLYKkqgqxPAvXMU273-hlrVp8gT/view",
  "B1_Green_Course_6B-10B/B1_10A-1_Idols_and_icons.pptx": "https://drive.google.com/file/d/1W_CskvkKBhcGML1da17OzaxXo4R7723O/view",
  "B1_Green_Course_6B-10B/B1_10A-1_Homework_sheet.pdf": "https://drive.google.com/file/d/1_GYcOC0qY6qDoV-eHcPjnLhwIPhLLZCQ/view",
  "B1_Green_Course_6B-10B/B1_10A-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1WSslU5dzf5y-SBhWBtVL0i7hcqHlK0bD/view",
  "B1_Green_Course_6B-10B/B1_10A-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1GWeZpDBJDXQ42vZatphCM8d4h0kgWSfI/view",
  "B1_Green_Course_6B-10B/B1_10A_Photocopiables.pdf": "https://drive.google.com/file/d/1pK8bUOuIq46TPZ1Ei_wlwOqE44fpMCiE/view",
  "B1_Green_Course_6B-10B/B1_10A-2_Idols_and_icons.pptx": "https://drive.google.com/file/d/19I2QGXn6FOWK8uvZkSF8UkhJOBeS25Xi/view",
  "B1_Green_Course_6B-10B/B1_10A-2_Homework_sheet.pdf": "https://drive.google.com/file/d/1oWMrTFCW0n_IwkzE_yQy3t_roXlUbwdF/view",
  "B1_Green_Course_6B-10B/B1_10A-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1U9UGFb0aGn8ayJ9Wm7xMxBpR8XSejEv2/view",
  "B1_Green_Course_6B-10B/B1_10A-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1X5NNL3gQZTpKWpuhyCD1dewT0Ox8t-qC/view",
  "B1_Green_Course_6B-10B/B1_10B-1_And_the_murderer_is.pptx": "https://drive.google.com/file/d/1iJFlQ5sIy15gJTNvY-aMpVhRWk-7MCjA/view",
  "B1_Green_Course_6B-10B/B1_10B-1_Homework_sheet.pdf": "https://drive.google.com/file/d/1KJkC9F11w6na-_BBwi6f4_-ACTJtvGhW/view",
  "B1_Green_Course_6B-10B/B1_10B-1_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1lWlSH0VR7hYKSJ6v1cDWLKnmjP3OdVym/view",
  "B1_Green_Course_6B-10B/B1_10B-1_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1aX2fcVUjOGnSA20vrZijN9TySnhqMe8w/view",
  "B1_Green_Course_6B-10B/B1_10B_Photocopiables.pdf": "https://drive.google.com/file/d/12K45sOyqh5oNhd3GIyRen_6EKZ-crV5h/view",
  "B1_Green_Course_6B-10B/B1_10B-2_And_the_murderer_is.pptx": "https://drive.google.com/file/d/1couoCwpYfDjMYUfMjHCcUQUdJjsWLkim/view",
  "B1_Green_Course_6B-10B/B1_10B-2_Homework_sheet.pdf": "https://drive.google.com/file/d/14OYrjhnx1mq1TWu225fYR6OJi8JlzGeV/view",
  "B1_Green_Course_6B-10B/B1_10B-2_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1RZNpANjvjvtRIGKFamL6rSCdr3bbb4mp/view",
  "B1_Green_Course_6B-10B/B1_10B-2_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1-A4WP7ix3gVqBxy1xkH-Y5_pgOyGlC63/view",
  "B1_Green_Course_6B-10B/B1_R9-10_Revise_and_Check_9_10.pptx": "https://drive.google.com/file/d/1w9XUnDPe0HJJ735WN9RAMBBxSA24xmMF/view",
  "B1_Green_Course_6B-10B/B1_R9-10_Homework_sheet.pdf": "https://drive.google.com/file/d/1vs_mvu5b7py0y79hx8bPqvGeJCwvkNW9/view",
  "B1_Green_Course_6B-10B/B1_R9-10_Homework_sheet_easier.pdf": "https://drive.google.com/file/d/1hP5_xOmLwUieldw0fS9Dlhoa23K052kC/view",
  "B1_Green_Course_6B-10B/B1_R9-10_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1meZfToMvFRnsqvTMptUd2wpSp-Z1Vszy/view",
  "B1_Green_Course_6B-10B/B1_Photocopiables_Teacher_notes_and_answers.pdf": "https://drive.google.com/file/d/1ohj4Vs8nefoCHosUKpH2hQT2d0-6Pb11/view",
  "B1_Green_Course_6B-10B/B1_Workbook_1A-5B_Teacher_answer_key.pdf": "https://drive.google.com/file/d/1ZRSJDeONUisyRZcBkYpObCZ6RPw677h2/view",
  "B1_Green_Course_6B-10B/B1_Workbook_6A-10B_Teacher_answer_key.pdf": "https://drive.google.com/file/d/13Fv150lisgdi5PVC5RbR2Nqg484xCfxI/view"
 },
 "names": {
  "EF-A2B1": "English File A2/B1 (blue) – full course",
  "EF-B1": "English File B1 (green) – full course, units 1–10",
  "CHEF": "Kitchen English for chefs – 10 lessons"
 },
 "courses": {
  "EF-A2B1": [
   {
    "id": "1B",
    "unit": 1,
    "title": "The perfect date?",
    "focus": "Present simple • describing people",
    "pages": "SB pp.8–9",
    "slides": 13,
    "file": "A2_Blue_Part1_Units1-6/A2_1B_The_perfect_date.pptx",
    "skills": {
     "Grammar": "Present simple",
     "Vocabulary": "describing people",
     "Reading": "Please date my dad!",
     "Listening": "Elspbeth's dates",
     "Speaking": "Find them a partner!"
    }
   },
   {
    "id": "1C",
    "unit": 1,
    "title": "The Remake Project",
    "focus": "Present continuous • clothes • prepositions of place",
    "pages": "SB pp.10–11",
    "slides": 13,
    "file": "A2_Blue_Part1_Units1-6/A2_1C_The_Remake_Project.pptx",
    "skills": {
     "Grammar": "Present continuous, prepositions of place",
     "Vocabulary": "clothes",
     "Listening": "The Milkmaid",
     "Speaking": "What do you usually wear…?",
     "Games & songs": "Picture memory"
    }
   },
   {
    "id": "2A",
    "unit": 2,
    "title": "OMG! Where's my passport?",
    "focus": "Past simple • holidays",
    "pages": "SB pp.14–15",
    "slides": 11,
    "file": "A2_Blue_Part1_Units1-6/A2_2A_Wheres_my_passport.pptx",
    "skills": {
     "Grammar": "Past simple",
     "Vocabulary": "holidays",
     "Reading": "Passport, tickets, money, phone",
     "Listening": "Marta's story",
     "Speaking": "Your last holiday",
     "Games & songs": "Holiday disaster!"
    }
   },
   {
    "id": "2B",
    "unit": 2,
    "title": "That's me in the picture!",
    "focus": "Past continuous • at, in, on",
    "pages": "SB pp.16–17",
    "slides": 12,
    "file": "A2_Blue_Part1_Units1-6/A2_2B_Thats_me_in_the_picture.pptx",
    "skills": {
     "Grammar": "Past continuous, at, in, on",
     "Reading": "A famous photo",
     "Listening": "Anya's photos",
     "Games & songs": "Alibi!"
    }
   },
   {
    "id": "2C",
    "unit": 2,
    "title": "One dark October evening",
    "focus": "Time sequencers and connectors",
    "pages": "SB pp.18–19",
    "slides": 10,
    "file": "A2_Blue_Part1_Units1-6/A2_2C_One_dark_October_evening.pptx",
    "skills": {
     "Grammar": "Time sequencers and connectors",
     "Listening": "Happy or sad ending?",
     "Speaking": "Retell the story"
    }
   },
   {
    "id": "R1-2",
    "unit": 2,
    "title": "Revise and Check – units 1 & 2",
    "focus": "Units 1 & 2 – test and games",
    "pages": "SB pp.20–21",
    "slides": 10,
    "file": "A2_Blue_Part1_Units1-6/A2_1-2_Revise_and_Check.pptx",
    "skills": {
     "Grammar": "Review of units 1–2",
     "Speaking": "Can you say this in English?",
     "Games & songs": "Back to the board"
    }
   },
   {
    "id": "3A",
    "unit": 3,
    "title": "TripAside",
    "focus": "be going to • airports",
    "pages": "SB pp.22–23",
    "slides": 8,
    "file": "A2_Blue_Part1_Units1-6/A2_3A_TripAside_going_to.pptx",
    "skills": {
     "Grammar": "be going to",
     "Vocabulary": "airports",
     "Reading": "No more boring stopovers!",
     "Speaking": "Plan a stopover tour!"
    }
   },
   {
    "id": "3B",
    "unit": 3,
    "title": "Put it in your calendar!",
    "focus": "Present continuous (future arrangements)",
    "pages": "SB pp.24–25",
    "slides": 9,
    "file": "A2_Blue_Part1_Units1-6/A2_3B_Put_it_in_your_calendar.pptx",
    "skills": {
     "Grammar": "Present continuous (future arrangements)",
     "Listening": "Jake and Sarah",
     "Games & songs": "How organized are you?"
    }
   },
   {
    "id": "3C",
    "unit": 3,
    "title": "Word games",
    "focus": "Defining relative clauses • paraphrasing",
    "pages": "SB pp.26–27",
    "slides": 9,
    "file": "A2_Blue_Part1_Units1-6/A2_3C_Word_games_relative_clauses.pptx",
    "skills": {
     "Grammar": "Defining relative clauses",
     "Vocabulary": "paraphrasing",
     "Reading": "A to Z",
     "Games & songs": "A to Z challenge"
    }
   },
   {
    "id": "4A",
    "unit": 4,
    "title": "Who does what?",
    "focus": "Present perfect + yet, just, already",
    "pages": "SB pp.30–31",
    "slides": 12,
    "file": "A2_Blue_Part1_Units1-6/A2_4A_Who_does_what_housework.pptx",
    "skills": {
     "Grammar": "Present perfect + yet, just, already",
     "Reading": "Housework headlines",
     "Listening": "The Lazy Person's Guide",
     "Speaking": "Your country / You"
    }
   },
   {
    "id": "4B",
    "unit": 4,
    "title": "In your basket",
    "focus": "Present perfect or past simple? • shopping",
    "pages": "SB pp.32–33",
    "slides": 12,
    "file": "A2_Blue_Part1_Units1-6/A2_4B_In_your_basket_shopping.pptx",
    "skills": {
     "Grammar": "Present perfect or past simple?",
     "Vocabulary": "shopping",
     "Reading": "The ice cream sellers",
     "Speaking": "Global chain stores"
    }
   },
   {
    "id": "4C",
    "unit": 4,
    "title": "#greatweekend",
    "focus": "something, anything, nothing • -ed / -ing adjectives",
    "pages": "SB pp.34–35",
    "slides": 9,
    "file": "A2_Blue_Part1_Units1-6/A2_4C_greatweekend.pptx",
    "skills": {
     "Grammar": "something, anything, nothing, -ed / -ing adjectives",
     "Reading": "A boring weekend?",
     "Listening": "The history of the weekend",
     "Games & songs": "One answer is a lie!"
    }
   },
   {
    "id": "R3-4",
    "unit": 4,
    "title": "Revise and Check – units 3 & 4",
    "focus": "Units 3 & 4 – test and games",
    "pages": "SB pp.36–37",
    "slides": 10,
    "file": "A2_Blue_Part1_Units1-6/A2_3-4_Revise_and_Check.pptx",
    "skills": {
     "Grammar": "Review of units 3–4",
     "Speaking": "Can you say this in English?",
     "Games & songs": "Revise and Check – units 3 & 4"
    }
   },
   {
    "id": "5A",
    "unit": 5,
    "title": "I want it NOW!",
    "focus": "Comparatives, as…as • numbers",
    "pages": "SB pp.38–39",
    "slides": 13,
    "file": "A2_Blue_Part1_Units1-6/A2_5A_I_want_it_NOW.pptx",
    "skills": {
     "Grammar": "Comparatives, as…as",
     "Vocabulary": "numbers",
     "Reading": "I want it, and I want it NOW!",
     "Listening": "How has your life changed?",
     "Speaking": "How fast is your life?",
     "Games & songs": "Compare us!"
    }
   },
   {
    "id": "5B",
    "unit": 5,
    "title": "Twelve lost wallets",
    "focus": "Superlatives (+ ever + present perfect)",
    "pages": "SB pp.40–41",
    "slides": 10,
    "file": "A2_Blue_Part1_Units1-6/A2_5B_Twelve_lost_wallets.pptx",
    "skills": {
     "Grammar": "Superlatives (+ ever + present perfect)",
     "Listening": "The most honest city?",
     "Speaking": "The most… you've ever…"
    }
   },
   {
    "id": "5C",
    "unit": 5,
    "title": "How much is enough?",
    "focus": "Quantifiers, too, (not) enough",
    "pages": "SB pp.42–43",
    "slides": 11,
    "file": "A2_Blue_Part1_Units1-6/A2_5C_How_much_is_enough.pptx",
    "skills": {
     "Grammar": "Quantifiers, too, (not) enough",
     "Reading": "Are they really good and bad?",
     "Speaking": "What do you drink?"
    }
   },
   {
    "id": "6A",
    "unit": 6,
    "title": "Think positive – or negative?",
    "focus": "will / won't (predictions) • opposite verbs",
    "pages": "SB pp.46–47",
    "slides": 10,
    "file": "A2_Blue_Part1_Units1-6/A2_6A_Think_positive.pptx",
    "skills": {
     "Grammar": "will / won't (predictions)",
     "Vocabulary": "opposite verbs",
     "Reading": "Why negative thinking can be positive",
     "Speaking": "Are you a positive thinker?",
     "Games & songs": "Optimist vs pessimist"
    }
   },
   {
    "id": "6B",
    "unit": 6,
    "title": "I'll always love you",
    "focus": "will / won't / shall (other uses) • verb + back",
    "pages": "SB pp.48–49",
    "slides": 10,
    "file": "A2_Blue_Part1_Units1-6/A2_6B_Ill_always_love_you.pptx",
    "skills": {
     "Grammar": "will / won't / shall (other uses)",
     "Vocabulary": "verb + back",
     "Reading": "\"I'll never forget you\"",
     "Speaking": "Do you…?",
     "Games & songs": "Promises, offers, decisions"
    }
   },
   {
    "id": "6C",
    "unit": 6,
    "title": "The meaning of dreaming",
    "focus": "Review of verb forms • modifiers",
    "pages": "SB pp.50–51",
    "slides": 11,
    "file": "A2_Blue_Part1_Units1-6/A2_6C_The_meaning_of_dreaming.pptx",
    "skills": {
     "Grammar": "Review of verb forms",
     "Vocabulary": "modifiers",
     "Listening": "Dr Melloni and the patient",
     "Speaking": "Dreams"
    }
   },
   {
    "id": "R5-6",
    "unit": 6,
    "title": "Revise and Check – units 5 & 6",
    "focus": "Units 5 & 6 – test and games",
    "pages": "SB pp.52–53",
    "slides": 10,
    "file": "A2_Blue_Part1_Units1-6/A2_5-6_Revise_and_Check.pptx",
    "skills": {
     "Grammar": "Review of units 5–6",
     "Speaking": "Can you say this in English?",
     "Games & songs": "Superlative auction"
    }
   },
   {
    "id": "7A",
    "unit": 7,
    "title": "First day nerves",
    "focus": "Uses of the infinitive with to",
    "pages": "SB pp.54–55",
    "slides": 11,
    "file": "A2_Blue_Part2_Units7-12/A2_7A_First_day_nerves.pptx",
    "skills": {
     "Grammar": "Uses of the infinitive with to",
     "Reading": "How to survive your first day",
     "Listening": "Simon and Claire",
     "Speaking": "Ask me!",
     "Games & songs": "How to survive…"
    }
   },
   {
    "id": "7B",
    "unit": 7,
    "title": "Happiness is…",
    "focus": "Uses of the gerund (verb + -ing)",
    "pages": "SB pp.56–57",
    "slides": 9,
    "file": "A2_Blue_Part2_Units7-12/A2_7B_Happiness_is.pptx",
    "skills": {
     "Grammar": "Uses of the gerund (verb + -ing)",
     "Reading": "Happiness is…",
     "Listening": "The Bank of Happiness",
     "Speaking": "Something / somewhere…",
     "Games & songs": "Happiness is… gallery"
    }
   },
   {
    "id": "7C",
    "unit": 7,
    "title": "Could you pass the test?",
    "focus": "have to, don't have to, must, mustn't",
    "pages": "SB pp.58–59",
    "slides": 10,
    "file": "A2_Blue_Part2_Units7-12/A2_7C_Could_you_pass_the_test.pptx",
    "skills": {
     "Grammar": "have to, don't have to, must, mustn't",
     "Reading": "Are the British really so bad at languages?",
     "Listening": "Max's tests",
     "Speaking": "Have you ever…?",
     "Games & songs": "Classroom rules"
    }
   },
   {
    "id": "8A",
    "unit": 8,
    "title": "Should I stay or should I go?",
    "focus": "should • get",
    "pages": "SB pp.62–63",
    "slides": 10,
    "file": "A2_Blue_Part2_Units7-12/A2_8A_Should_I_stay_or_go.pptx",
    "skills": {
     "Grammar": "should, get",
     "Reading": "Dear Graham",
     "Speaking": "What's the problem?",
     "Games & songs": "Agony aunt"
    }
   },
   {
    "id": "8B",
    "unit": 8,
    "title": "Murphy's Law",
    "focus": "if + present, will + infinitive",
    "pages": "SB pp.64–65",
    "slides": 9,
    "file": "A2_Blue_Part2_Units7-12/A2_8B_Murphys_Law_first_conditional.pptx",
    "skills": {
     "Grammar": "if + present, will + infinitive",
     "Reading": "If something can go wrong…",
     "Listening": "Peter and Sue",
     "Games & songs": "Murphy's Law challenge"
    }
   },
   {
    "id": "8C",
    "unit": 8,
    "title": "Who is Vivienne?",
    "focus": "Possessive pronouns • adverbs of manner",
    "pages": "SB pp.66–67",
    "slides": 10,
    "file": "A2_Blue_Part2_Units7-12/A2_8C_Who_is_Vivienne.pptx",
    "skills": {
     "Grammar": "Possessive pronouns, adverbs of manner",
     "Listening": "Who is Vivienne? – The ending",
     "Games & songs": "Say it… angrily!"
    }
   },
   {
    "id": "R7-8",
    "unit": 8,
    "title": "Revise and Check – units 7 & 8",
    "focus": "Units 7 & 8 – test and games",
    "pages": "SB pp.68–69",
    "slides": 10,
    "file": "A2_Blue_Part2_Units7-12/A2_7-8_Revise_and_Check.pptx",
    "skills": {
     "Grammar": "Review of units 7–8",
     "Speaking": "Can you say this in English?",
     "Games & songs": "Queue race"
    }
   },
   {
    "id": "9A",
    "unit": 9,
    "title": "Beware of the dog",
    "focus": "if + past, would + infinitive • animals",
    "pages": "SB pp.70–71",
    "slides": 11,
    "file": "A2_Blue_Part2_Units7-12/A2_9A_Beware_of_the_dog.pptx",
    "skills": {
     "Grammar": "if + past, would + infinitive",
     "Vocabulary": "animals",
     "Speaking": "Animals and you",
     "Games & songs": "Would you know what to do?"
    }
   },
   {
    "id": "9B",
    "unit": 9,
    "title": "Fearof.net",
    "focus": "Present perfect + for and since",
    "pages": "SB pp.72–73",
    "slides": 11,
    "file": "A2_Blue_Part2_Units7-12/A2_9B_Fearof_net.pptx",
    "skills": {
     "Grammar": "Present perfect + for and since",
     "Reading": "Fearof.net",
     "Listening": "Julia and Chloe",
     "Games & songs": "Find someone who…"
    }
   },
   {
    "id": "9C",
    "unit": 9,
    "title": "Scream queens",
    "focus": "Present perfect or past simple? (2) • biographies",
    "pages": "SB pp.74–75",
    "slides": 10,
    "file": "A2_Blue_Part2_Units7-12/A2_9C_Scream_queens.pptx",
    "skills": {
     "Grammar": "Present perfect or past simple? (2)",
     "Vocabulary": "biographies",
     "Reading": "Like mother, like daughter",
     "Listening": "Famous father, famous son",
     "Speaking": "An older person you know"
    }
   },
   {
    "id": "10A",
    "unit": 10,
    "title": "Into the net",
    "focus": "Expressing movement • sports",
    "pages": "SB pp.78–79",
    "slides": 11,
    "file": "A2_Blue_Part2_Units7-12/A2_10A_Into_the_net_sport.pptx",
    "skills": {
     "Grammar": "Expressing movement",
     "Vocabulary": "sports",
     "Reading": "Why aren't women's sports as popular as men's?",
     "Speaking": "Sport – you love it or you hate it",
     "Games & songs": "Sports commentator"
    }
   },
   {
    "id": "10B",
    "unit": 10,
    "title": "Early birds",
    "focus": "Word order of phrasal verbs",
    "pages": "SB pp.80–81",
    "slides": 10,
    "file": "A2_Blue_Part2_Units7-12/A2_10B_Early_birds_phrasal_verbs.pptx",
    "skills": {
     "Grammar": "Word order of phrasal verbs",
     "Listening": "Getting up early",
     "Speaking": "Getting up",
     "Games & songs": "Phrasal verb charades"
    }
   },
   {
    "id": "10C",
    "unit": 10,
    "title": "International inventions",
    "focus": "The passive • people from different countries",
    "pages": "SB pp.82–83",
    "slides": 10,
    "file": "A2_Blue_Part2_Units7-12/A2_10C_International_inventions_passive.pptx",
    "skills": {
     "Grammar": "The passive",
     "Vocabulary": "people from different countries",
     "Listening": "Invented by women",
     "Games & songs": "Who invented it?"
    }
   },
   {
    "id": "R9-10",
    "unit": 10,
    "title": "Revise and Check – units 9 & 10",
    "focus": "Units 9 & 10 – test and games",
    "pages": "SB pp.84–85",
    "slides": 10,
    "file": "A2_Blue_Part2_Units7-12/A2_9-10_Revise_and_Check.pptx",
    "skills": {
     "Grammar": "Review of units 9–10",
     "Speaking": "Can you say this in English?",
     "Games & songs": "Animal 20 questions"
    }
   },
   {
    "id": "11A",
    "unit": 11,
    "title": "Ask the teacher",
    "focus": "used to • school subjects",
    "pages": "SB pp.86–87",
    "slides": 9,
    "file": "A2_Blue_Part2_Units7-12/A2_11A_Ask_the_teacher_used_to.pptx",
    "skills": {
     "Grammar": "used to",
     "Vocabulary": "school subjects",
     "Reading": "Fame Academy",
     "Listening": "Did you like school?",
     "Speaking": "When you were at school…",
     "Games & songs": "When I was little…"
    }
   },
   {
    "id": "11B",
    "unit": 11,
    "title": "Help! I can't decide!",
    "focus": "might • noun formation",
    "pages": "SB pp.88–89",
    "slides": 10,
    "file": "A2_Blue_Part2_Units7-12/A2_11B_I_cant_decide_might.pptx",
    "skills": {
     "Grammar": "might, noun formation",
     "Listening": "Nancy is packing",
     "Speaking": "Are you indecisive?",
     "Games & songs": "I'm not sure…"
    }
   },
   {
    "id": "11C",
    "unit": 11,
    "title": "Twinstrangers.net",
    "focus": "so, neither + auxiliaries • similarities",
    "pages": "SB pp.90–91",
    "slides": 9,
    "file": "A2_Blue_Part2_Units7-12/A2_11C_Twinstrangers_so_neither.pptx",
    "skills": {
     "Grammar": "so, neither + auxiliaries",
     "Vocabulary": "similarities",
     "Reading": "Twin Strangers",
     "Listening": "Meeting my doppelgänger",
     "Games & songs": "Find your twin!"
    }
   },
   {
    "id": "12A",
    "unit": 12,
    "title": "Unbelievable!",
    "focus": "Past perfect • time expressions",
    "pages": "SB pp.94–95",
    "slides": 8,
    "file": "A2_Blue_Part2_Units7-12/A2_12A_Unbelievable_past_perfect.pptx",
    "skills": {
     "Grammar": "Past perfect, time expressions",
     "Reading": "Three news stories",
     "Speaking": "Tell the story!"
    }
   },
   {
    "id": "12B",
    "unit": 12,
    "title": "Think before you speak",
    "focus": "Reported speech • say or tell?",
    "pages": "SB pp.96–97",
    "slides": 9,
    "file": "A2_Blue_Part2_Units7-12/A2_12B_Think_before_you_speak.pptx",
    "skills": {
     "Grammar": "Reported speech, say or tell?",
     "Reading": "Blowing in the wind",
     "Listening": "Rosemary and Iris",
     "Games & songs": "One answer is invented!"
    }
   },
   {
    "id": "12C",
    "unit": 12,
    "title": "The English File quiz",
    "focus": "Questions without auxiliaries",
    "pages": "SB pp.98–99",
    "slides": 8,
    "file": "A2_Blue_Part2_Units7-12/A2_12C_The_English_File_quiz.pptx",
    "skills": {
     "Grammar": "Questions without auxiliaries",
     "Listening": "Pub quiz",
     "Games & songs": "The English File quiz"
    }
   },
   {
    "id": "R11-12",
    "unit": 12,
    "title": "Revise and Check – units 11 & 12",
    "focus": "Units 11 & 12 – final test and games",
    "pages": "SB pp.100–101",
    "slides": 10,
    "file": "A2_Blue_Part2_Units7-12/A2_11-12_Revise_and_Check.pptx",
    "skills": {
     "Grammar": "Review of units 11–12",
     "Speaking": "Can you say this in English?",
     "Games & songs": "The big final quiz!"
    }
   }
  ],
  "EF-B1": [
   {
    "id": "1A-1",
    "unit": 1,
    "title": "Eating in… and out",
    "focus": "food and cooking • short and long vowels",
    "pages": "SB pp.6–7",
    "slides": 16,
    "skills": {
     "Vocabulary": "food and cooking",
     "Speaking": "short and long vowels",
     "Listening": "Your food profile",
     "Reading": "Eat at the right time!"
    },
    "file": "B1_Green_Course_6B-10B/B1_1A-1_Eating_in_and_out.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_1A-1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_1A-1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_1A-1_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_1A_Photocopiables.pdf"
   },
   {
    "id": "1A-2",
    "unit": 1,
    "title": "Eating in… and out",
    "focus": "A chef's story • present simple and continuous",
    "pages": "SB pp.8–9",
    "slides": 15,
    "skills": {
     "Listening": "A chef's story",
     "Grammar": "present simple and continuous",
     "Speaking": "agreeing and disagreeing"
    },
    "file": "B1_Green_Course_6B-10B/B1_1A-2_Eating_in_and_out.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_1A-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_1A-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_1A-2_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_1A_Photocopiables.pdf"
   },
   {
    "id": "1B-1",
    "unit": 1,
    "title": "Modern families",
    "focus": "family • future forms",
    "pages": "SB pp.10–11",
    "slides": 15,
    "skills": {
     "Vocabulary": "family",
     "Grammar": "future forms",
     "Speaking": "sentence stress"
    },
    "file": "B1_Green_Course_6B-10B/B1_1B-1_Modern_families.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_1B-1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_1B-1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_1B-1_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_1B_Photocopiables.pdf"
   },
   {
    "id": "1B-2",
    "unit": 1,
    "title": "Modern families",
    "focus": "adjectives of personality • word stress, prefixes",
    "pages": "SB pp.12–13",
    "slides": 16,
    "skills": {
     "Vocabulary": "adjectives of personality",
     "Speaking": "word stress, prefixes",
     "Reading": "How birth order influences you",
     "Listening": "Brothers and sisters"
    },
    "file": "B1_Green_Course_6B-10B/B1_1B-2_Modern_families.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_1B-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_1B-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_1B-2_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_1B_Photocopiables.pdf"
   },
   {
    "id": "PE1",
    "unit": 1,
    "title": "Meeting the parents",
    "focus": "Practical English Episode 1 • reacting to what people say",
    "pages": "SB pp.14–15",
    "slides": 15,
    "skills": {
     "Listening": "Practical English Episode 1",
     "Speaking": "reacting to what people say"
    },
    "file": "B1_Green_Course_6B-10B/B1_PE1_Meeting_the_parents.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_PE1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_PE1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_PE1_Teacher_answer_key.pdf"
   },
   {
    "id": "2A-1",
    "unit": 2,
    "title": "Spending money",
    "focus": "money • o and or",
    "pages": "SB pp.16–17",
    "slides": 17,
    "skills": {
     "Vocabulary": "money",
     "Speaking": "o and or",
     "Reading": "One woman's 'no-spend year'"
    },
    "file": "B1_Green_Course_6B-10B/B1_2A-1_Spending_money.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_2A-1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_2A-1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_2A-1_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_2A_Photocopiables.pdf"
   },
   {
    "id": "2A-2",
    "unit": 2,
    "title": "Spending money",
    "focus": "present perfect or past simple? • Have you ever…?",
    "pages": "SB pp.18–19",
    "slides": 15,
    "skills": {
     "Grammar": "present perfect or past simple?",
     "Speaking": "Have you ever…?",
     "Listening": "Scams and scammers"
    },
    "file": "B1_Green_Course_6B-10B/B1_2A-2_Spending_money.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_2A-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_2A-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_2A-2_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_2A_Photocopiables.pdf"
   },
   {
    "id": "2B-1",
    "unit": 2,
    "title": "Changing lives",
    "focus": "Adelante Africa • PP + for / since · PP continuous",
    "pages": "SB pp.20–21",
    "slides": 15,
    "skills": {
     "Listening": "Adelante Africa",
     "Grammar": "PP + for / since · PP continuous",
     "Speaking": "sentence stress"
    },
    "file": "B1_Green_Course_6B-10B/B1_2B-1_Changing_lives.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_2B-1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_2B-1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_2B-1_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_2B_Photocopiables.pdf"
   },
   {
    "id": "2B-2",
    "unit": 2,
    "title": "Changing lives",
    "focus": "The polar challenge • strong adjectives",
    "pages": "SB pp.22–23",
    "slides": 13,
    "skills": {
     "Reading": "The polar challenge",
     "Vocabulary": "strong adjectives",
     "Listening": "The Great OUP Bake Sale"
    },
    "file": "B1_Green_Course_6B-10B/B1_2B-2_Changing_lives.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_2B-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_2B-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_2B-2_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_2B_Photocopiables.pdf"
   },
   {
    "id": "R1-2",
    "unit": 2,
    "title": "Revise and Check 1&2",
    "focus": "present, future, present perfect • food, family, money, adjectives",
    "pages": "SB pp.24–25",
    "slides": 12,
    "skills": {
     "Grammar": "present, future, present perfect",
     "Vocabulary": "food, family, money, adjectives",
     "Games & songs": "auction · noughts and crosses · dice"
    },
    "file": "B1_Green_Course_6B-10B/B1_R1-2_Revise_and_Check_1-2.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_R1-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_R1-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_R1-2_Teacher_answer_key.pdf"
   },
   {
    "id": "3A-1",
    "unit": 3,
    "title": "Survive the drive",
    "focus": "transport • /ʃ/, /dʒ/, /tʃ/",
    "pages": "SB pp.26–27",
    "slides": 17,
    "skills": {
     "Vocabulary": "transport",
     "Speaking": "/ʃ/, /dʒ/, /tʃ/",
     "Reading": "The Top Gear race"
    },
    "file": "B1_Green_Course_6B-10B/B1_3A-1_Survive_the_drive.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_3A-1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_3A-1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_3A-1_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_3A_Photocopiables.pdf"
   },
   {
    "id": "3A-2",
    "unit": 3,
    "title": "Survive the drive",
    "focus": "comparatives & superlatives • What's the most dangerous thing?",
    "pages": "SB pp.28–29",
    "slides": 16,
    "skills": {
     "Grammar": "comparatives & superlatives",
     "Listening": "What's the most dangerous thing?",
     "Speaking": "linking",
     "Writing": "an article for a website"
    },
    "file": "B1_Green_Course_6B-10B/B1_3A-2_Survive_the_drive.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_3A-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_3A-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_3A-2_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_3A_Photocopiables.pdf"
   },
   {
    "id": "3B-1",
    "unit": 3,
    "title": "Men, women, and children",
    "focus": "Stereotypes: true or not? • articles: a / an, the, no article",
    "pages": "SB pp.30–31",
    "slides": 14,
    "skills": {
     "Speaking": "Stereotypes: true or not?",
     "Grammar": "articles: a / an, the, no article"
    },
    "file": "B1_Green_Course_6B-10B/B1_3B-1_Men_women_and_children.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_3B-1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_3B-1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_3B-1_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_3B_Photocopiables.pdf"
   },
   {
    "id": "3B-2",
    "unit": 3,
    "title": "Men, women, and children",
    "focus": "Pink for girls, blue for boys? • Toys and childhood",
    "pages": "SB pp.32–33",
    "slides": 14,
    "skills": {
     "Listening": "Pink for girls, blue for boys?",
     "Speaking": "Toys and childhood",
     "Vocabulary": "verbs / adjectives + prepositions"
    },
    "file": "B1_Green_Course_6B-10B/B1_3B-2_Men_women_and_children.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_3B-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_3B-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_3B-2_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_3B_Photocopiables.pdf"
   },
   {
    "id": "PE2",
    "unit": 3,
    "title": "A difficult celebrity",
    "focus": "Practical English Episode 2 • giving opinions, agreeing, disagreeing",
    "pages": "SB pp.34–35",
    "slides": 16,
    "skills": {
     "Listening": "Practical English Episode 2",
     "Speaking": "giving opinions, agreeing, disagreeing"
    },
    "file": "B1_Green_Course_6B-10B/B1_PE2_A_difficult_celebrity.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_PE2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_PE2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_PE2_Teacher_answer_key.pdf"
   },
   {
    "id": "4A-1",
    "unit": 4,
    "title": "Bad manners?",
    "focus": "phone language • have to, must, should",
    "pages": "SB pp.36–37",
    "slides": 15,
    "skills": {
     "Vocabulary": "phone language",
     "Grammar": "have to, must, should",
     "Speaking": "silent consonants"
    },
    "file": "B1_Green_Course_6B-10B/B1_4A-1_Bad_manners.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_4A-1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_4A-1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_4A-1_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_4A_Photocopiables.pdf"
   },
   {
    "id": "4A-2",
    "unit": 4,
    "title": "Bad manners?",
    "focus": "Debrett's guide to modern manners • Rude relatives",
    "pages": "SB pp.38–39",
    "slides": 11,
    "skills": {
     "Reading": "Debrett's guide to modern manners",
     "Listening": "Rude relatives",
     "Speaking": "Good or bad manners?"
    },
    "file": "B1_Green_Course_6B-10B/B1_4A-2_Bad_manners.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_4A-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_4A-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_4A-2_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_4A_Photocopiables.pdf"
   },
   {
    "id": "4B-1",
    "unit": 4,
    "title": "Yes, I can!",
    "focus": "can, could, be able to • sentence stress",
    "pages": "SB pp.40–41",
    "slides": 15,
    "skills": {
     "Grammar": "can, could, be able to",
     "Speaking": "sentence stress",
     "Listening": "Learning the trumpet in 20 hours"
    },
    "file": "B1_Green_Course_6B-10B/B1_4B-1_Yes_I_can.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_4B-1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_4B-1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_4B-1_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_4B_Photocopiables.pdf"
   },
   {
    "id": "4B-2",
    "unit": 4,
    "title": "Yes, I can!",
    "focus": "-ed / -ing adjectives • Tips for practising English",
    "pages": "SB pp.42–43",
    "slides": 13,
    "skills": {
     "Vocabulary": "-ed / -ing adjectives",
     "Reading": "Tips for practising English",
     "Grammar": "reflexive pronouns",
     "Listening": "Alex Rawlings, 11 languages"
    },
    "file": "B1_Green_Course_6B-10B/B1_4B-2_Yes_I_can.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_4B-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_4B-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_4B-2_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_4B_Photocopiables.pdf"
   },
   {
    "id": "R3-4",
    "unit": 4,
    "title": "Revise and Check 3&4",
    "focus": "comparatives, articles, modals, be able to • transport, prepositions, phones, feelings",
    "pages": "SB pp.44–45",
    "slides": 13,
    "skills": {
     "Grammar": "comparatives, articles, modals, be able to",
     "Vocabulary": "transport, prepositions, phones, feelings",
     "Listening": "Can you understand these people?",
     "Speaking": "30-second challenge"
    },
    "file": "B1_Green_Course_6B-10B/B1_R3-4_Revise_and_Check_3_4.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_R3-4_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_R3-4_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_R3-4_Teacher_answer_key.pdf"
   },
   {
    "id": "5A-1",
    "unit": 5,
    "title": "Sporting superstitions",
    "focus": "sport • /ɔː/ and /ɜː/",
    "pages": "SB pp.46–47",
    "slides": 14,
    "skills": {
     "Vocabulary": "sport",
     "Speaking": "/ɔː/ and /ɜː/",
     "Reading": "Do 'lucky socks' really work?"
    },
    "file": "B1_Green_Course_6B-10B/B1_5A-1_Sporting_superstitions.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_5A-1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_5A-1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_5A-1_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_5A_Photocopiables.pdf"
   },
   {
    "id": "5A-2",
    "unit": 5,
    "title": "Sporting superstitions",
    "focus": "An interview with a referee • past simple, continuous, perfect",
    "pages": "SB pp.48–49",
    "slides": 14,
    "skills": {
     "Listening": "An interview with a referee",
     "Grammar": "past simple, continuous, perfect",
     "Speaking": "Telling an anecdote"
    },
    "file": "B1_Green_Course_6B-10B/B1_5A-2_Sporting_superstitions.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_5A-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_5A-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_5A-2_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_5A_Photocopiables.pdf"
   },
   {
    "id": "5B-1",
    "unit": 5,
    "title": "#thewaywemet",
    "focus": "The way we met • used to / usually",
    "pages": "SB pp.50–51",
    "slides": 15,
    "skills": {
     "Reading": "The way we met",
     "Grammar": "used to / usually",
     "Speaking": "the letter s, used to"
    },
    "file": "B1_Green_Course_6B-10B/B1_5B-1_thewaywemet.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_5B-1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_5B-1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_5B-1_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_5B_Photocopiables.pdf"
   },
   {
    "id": "5B-2",
    "unit": 5,
    "title": "#thewaywemet",
    "focus": "relationships • Five facts about friendship",
    "pages": "SB pp.52–53",
    "slides": 13,
    "skills": {
     "Vocabulary": "relationships",
     "Listening": "Five facts about friendship",
     "Speaking": "Presenting an opinion"
    },
    "file": "B1_Green_Course_6B-10B/B1_5B-2_thewaywemet.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_5B-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_5B-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_5B-2_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_5B_Photocopiables.pdf"
   },
   {
    "id": "PE3",
    "unit": 5,
    "title": "Old friends",
    "focus": "Episode 3 • making requests",
    "pages": "SB pp.54–55",
    "slides": 16,
    "skills": {
     "Listening": "Episode 3",
     "Speaking": "meeting an old friend"
    },
    "file": "B1_Green_Course_6B-10B/B1_PE3_Old_friends.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_PE3_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_PE3_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_PE3_Teacher_answer_key.pdf"
   },
   {
    "id": "6A-1",
    "unit": 6,
    "title": "Behind the scenes",
    "focus": "The world of extras • the passive (all tenses)",
    "pages": "SB pp.56–57",
    "slides": 14,
    "skills": {
     "Reading": "The world of extras",
     "Grammar": "the passive (all tenses)",
     "Speaking": "past participles"
    },
    "file": "B1_Green_Course_6B-10B/B1_6A-1_Behind_the_scenes.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_6A-1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_6A-1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_6A-1_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_6A_Photocopiables.pdf"
   },
   {
    "id": "6A-2",
    "unit": 6,
    "title": "Behind the scenes",
    "focus": "cinema • Spielberg's interpreter",
    "pages": "SB pp.58–59",
    "slides": 13,
    "skills": {
     "Vocabulary": "cinema",
     "Listening": "Spielberg's interpreter",
     "Speaking": "Film quiz + cinema interview"
    },
    "file": "B1_Green_Course_6B-10B/B1_6A-2_Behind_the_scenes.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_6A-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_6A-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_6A-2_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_6A_Photocopiables.pdf"
   },
   {
    "id": "6B-1",
    "unit": 6,
    "title": "Every picture tells a story",
    "focus": "What your profile photo says • must, might, can't (deduction)",
    "pages": "SB pp.60–61",
    "slides": 15,
    "skills": {
     "Grammar": "Modals of deduction: might, can't, must",
     "Reading": "What your profile photo says",
     "Speaking": "Who are they?",
     "Games & songs": "What's in my bag?"
    },
    "file": "B1_Green_Course_6B-10B/B1_6B-1_Every_picture_tells_a_story.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_6B-1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_6B-1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_6B-1_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_6B_Photocopiables.pdf"
   },
   {
    "id": "6B-2",
    "unit": 6,
    "title": "Every picture tells a story",
    "focus": "the body + body verbs • diphthongs",
    "pages": "SB pp.62–63",
    "slides": 17,
    "skills": {
     "Vocabulary": "The body, describing people",
     "Reading": "Can you learn charisma?",
     "Listening": "A day with a personal stylist",
     "Games & songs": "Which part of the body…?"
    },
    "file": "B1_Green_Course_6B-10B/B1_6B-2_Every_picture_tells_a_story.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_6B-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_6B-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_6B-2_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_6B_Photocopiables.pdf"
   },
   {
    "id": "R5-6",
    "unit": 6,
    "title": "Revise and Check 5&6",
    "focus": "Grammar of Files 5 & 6 • sport, relationships, cinema, body",
    "pages": "SB pp.64–65",
    "slides": 15,
    "skills": {
     "Grammar": "Review of units 5–6",
     "Speaking": "Can you say this in English?",
     "Games & songs": "Two truths and a lie"
    },
    "file": "B1_Green_Course_6B-10B/B1_R5-6_Revise_and_Check_5_6.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_R5-6_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_R5-6_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_R5-6_Teacher_answer_key.pdf"
   },
   {
    "id": "7A-1",
    "unit": 7,
    "title": "Live and learn",
    "focus": "Education • school subjects",
    "pages": "SB pp.66–67",
    "slides": 16,
    "file": "B1_Green_Course_6B-10B/B1_7A-1_Live_and_learn.pptx",
    "skills": {
     "Vocabulary": "Education, school subjects",
     "Listening": "Chinese v British",
     "Speaking": "Your education"
    },
    "hw": "B1_Green_Course_6B-10B/B1_7A-1_Homework_sheet.pdf",
    "key": "B1_Green_Course_6B-10B/B1_7A-1_Teacher_answer_key.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_7A-1_Homework_sheet_easier.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_7A_Photocopiables.pdf"
   },
   {
    "id": "7A-2",
    "unit": 7,
    "title": "Is it worth going to uni?",
    "focus": "First conditional & future time clauses",
    "pages": "SB pp.68–69",
    "slides": 17,
    "file": "B1_Green_Course_6B-10B/B1_7A-2_Live_and_learn.pptx",
    "skills": {
     "Grammar": "First conditional & future time clauses",
     "Reading": "Is it really worth going to uni?",
     "Speaking": "Exams!",
     "Games & songs": "The grammar auction"
    },
    "hw": "B1_Green_Course_6B-10B/B1_7A-2_Homework_sheet.pdf",
    "key": "B1_Green_Course_6B-10B/B1_7A-2_Teacher_answer_key.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_7A-2_Homework_sheet_easier.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_7A_Photocopiables.pdf"
   },
   {
    "id": "7B-1",
    "unit": 7,
    "title": "The hotel of Mum and Dad",
    "focus": "Living with your parents • second conditional; 1st or 2nd?",
    "pages": "SB pp.70–71",
    "slides": 15,
    "skills": {
     "Grammar": "Second conditional",
     "Reading": "Where do they live?",
     "Speaking": "Talk to a partner",
     "Games & songs": "Would you rather…?"
    },
    "file": "B1_Green_Course_6B-10B/B1_7B-1_The_hotel_of_Mum_and_Dad.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_7B-1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_7B-1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_7B-1_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_7B_Photocopiables.pdf"
   },
   {
    "id": "7B-2",
    "unit": 7,
    "title": "The hotel of Mum and Dad",
    "focus": "houses • the letter c",
    "pages": "SB pp.72–73",
    "slides": 16,
    "skills": {
     "Vocabulary": "Houses, describing your home",
     "Listening": "Handel or Hendrix?",
     "Speaking": "Your dream home"
    },
    "file": "B1_Green_Course_6B-10B/B1_7B-2_The_hotel_of_Mum_and_Dad.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_7B-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_7B-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_7B-2_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_7B_Photocopiables.pdf"
   },
   {
    "id": "PE4",
    "unit": 7,
    "title": "Boys' night out",
    "focus": "making and responding to suggestions • making an excuse, apologizing",
    "pages": "SB pp.74–75",
    "slides": 18,
    "skills": {
     "Speaking": "making and responding to suggestions"
    },
    "file": "B1_Green_Course_6B-10B/B1_PE4_Boys_night_out.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_PE4_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_PE4_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_PE4_Teacher_answer_key.pdf"
   },
   {
    "id": "8A-1",
    "unit": 8,
    "title": "The right job for you",
    "focus": "work • word stress",
    "pages": "SB pp.76–77",
    "slides": 17,
    "skills": {
     "Grammar": "gerunds and infinitives",
     "Vocabulary": "Work",
     "Speaking": "Someone you know",
     "Games & songs": "What's my job?"
    },
    "file": "B1_Green_Course_6B-10B/B1_8A-1_The_right_job_for_you.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_8A-1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_8A-1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_8A-1_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_8A_Photocopiables.pdf"
   },
   {
    "id": "8A-2",
    "unit": 8,
    "title": "The right job for you",
    "focus": "Dragons' Den • A contestant's story",
    "pages": "SB pp.78–79",
    "slides": 13,
    "skills": {
     "Vocabulary": "Business ideas, making a pitch",
     "Reading": "In the Dragons' Den",
     "Listening": "The famous Tangle Teezer pitch",
     "Speaking": "Your pitch!",
     "Games & songs": "Dragons' Den – class vote"
    },
    "file": "B1_Green_Course_6B-10B/B1_8A-2_The_right_job_for_you.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_8A-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_8A-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_8A-2_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_8A_Photocopiables.pdf"
   },
   {
    "id": "8B-1",
    "unit": 8,
    "title": "Have a nice day!",
    "focus": "When 'happy to help' becomes a problem • reported speech: sentences + questions",
    "pages": "SB pp.80–81",
    "slides": 14,
    "skills": {
     "Grammar": "Reported speech",
     "Vocabulary": "shopping",
     "Reading": "Who says it?",
     "Games & songs": "The reporter"
    },
    "file": "B1_Green_Course_6B-10B/B1_8B-1_Have_a_nice_day.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_8B-1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_8B-1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_8B-1_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_8B_Photocopiables.pdf"
   },
   {
    "id": "8B-2",
    "unit": 8,
    "title": "Have a nice day!",
    "focus": "Going the extra mile • United Breaks Guitars",
    "pages": "SB pp.82–83",
    "slides": 15,
    "skills": {
     "Grammar": "making nouns from verbs",
     "Vocabulary": "Customer service",
     "Reading": "Going the extra mile",
     "Listening": "Bad customer service",
     "Speaking": "I want to speak to the manager!",
     "Games & songs": "United Breaks Guitars"
    },
    "file": "B1_Green_Course_6B-10B/B1_8B-2_Have_a_nice_day.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_8B-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_8B-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_8B-2_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_8B_Photocopiables.pdf"
   },
   {
    "id": "R7-8",
    "unit": 8,
    "title": "Revise and Check 7&8",
    "focus": "conditionals · gerund or infinitive · reported speech • education · houses · work · shopping",
    "pages": "SB pp.84–85",
    "slides": 13,
    "skills": {
     "Grammar": "Review of units 7–8",
     "Speaking": "Can you say this in English?",
     "Games & songs": "Hot seat"
    },
    "file": "B1_Green_Course_6B-10B/B1_R7-8_Revise_and_Check_7_8.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_R7-8_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_R7-8_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_R7-8_Teacher_answer_key.pdf"
   },
   {
    "id": "9A-1",
    "unit": 9,
    "title": "Lucky encounters",
    "focus": "Helped by a stranger • third conditional",
    "pages": "SB pp.86–87",
    "slides": 15,
    "skills": {
     "Grammar": "Third conditional",
     "Listening": "What would you do if…?",
     "Games & songs": "The chain of disaster"
    },
    "file": "B1_Green_Course_6B-10B/B1_9A-1_Lucky_encounters.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_9A-1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_9A-1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_9A-1_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_9A_Photocopiables.pdf"
   },
   {
    "id": "9A-2",
    "unit": 9,
    "title": "Lucky encounters",
    "focus": "How to improve your luck • making adjectives and adverbs",
    "pages": "SB pp.88–89",
    "slides": 14,
    "skills": {
     "Grammar": "Making adjectives and adverbs",
     "Reading": "How to improve your luck",
     "Games & songs": "Deal or No Deal"
    },
    "file": "B1_Green_Course_6B-10B/B1_9A-2_Lucky_encounters.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_9A-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_9A-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_9A-2_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_9A_Photocopiables.pdf"
   },
   {
    "id": "9B-1",
    "unit": 9,
    "title": "Digital detox",
    "focus": "electronic devices • switch it on, turn it up…",
    "pages": "SB pp.90–91",
    "slides": 15,
    "skills": {
     "Vocabulary": "Electronic devices, phrasal verbs",
     "Reading": "Less time online",
     "Speaking": "Talk about your devices"
    },
    "file": "B1_Green_Course_6B-10B/B1_9B-1_Digital_detox.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_9B-1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_9B-1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_9B-1_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_9B_Photocopiables.pdf"
   },
   {
    "id": "9B-2",
    "unit": 9,
    "title": "Digital detox",
    "focus": "quantifiers • ough and augh",
    "pages": "SB pp.92–93",
    "slides": 15,
    "skills": {
     "Grammar": "Quantifiers, un- prefix",
     "Reading": "11 ways to tidy up your digital life",
     "Speaking": "How organized is your digital life?"
    },
    "file": "B1_Green_Course_6B-10B/B1_9B-2_Digital_detox.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_9B-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_9B-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_9B-2_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_9B_Photocopiables.pdf"
   },
   {
    "id": "PE5",
    "unit": 9,
    "title": "Unexpected events",
    "focus": "Episode 5 • indirect questions",
    "pages": "SB pp.94–95",
    "slides": 16,
    "skills": {
     "Listening": "Episode 5",
     "Speaking": "indirect questions"
    },
    "file": "B1_Green_Course_6B-10B/B1_PE5_Unexpected_events.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_PE5_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_PE5_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_PE5_Teacher_answer_key.pdf"
   },
   {
    "id": "10A-1",
    "unit": 10,
    "title": "Idols and icons",
    "focus": "The year our heroes died • relative clauses",
    "pages": "SB pp.96–97",
    "slides": 14,
    "skills": {
     "Grammar": "Relative clauses: defining and non-defining",
     "Reading": "The year our heroes died",
     "Games & songs": "What do you call…?"
    },
    "file": "B1_Green_Course_6B-10B/B1_10A-1_Idols_and_icons.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_10A-1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_10A-1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_10A-1_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_10A_Photocopiables.pdf"
   },
   {
    "id": "10A-2",
    "unit": 10,
    "title": "Idols and icons",
    "focus": "British design icons • My icons",
    "pages": "SB pp.98–99",
    "slides": 13,
    "skills": {
     "Grammar": "Compound nouns",
     "Listening": "British design",
     "Speaking": "People, things & places",
     "Games & songs": "Compound nouns race"
    },
    "file": "B1_Green_Course_6B-10B/B1_10A-2_Idols_and_icons.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_10A-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_10A-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_10A-2_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_10A_Photocopiables.pdf"
   },
   {
    "id": "10B-1",
    "unit": 10,
    "title": "And the murderer is…",
    "focus": "crime • Jack the Ripper",
    "pages": "SB pp.100–101",
    "slides": 14,
    "skills": {
     "Grammar": "question tags",
     "Vocabulary": "Crime",
     "Reading": "The greatest unsolved crime",
     "Listening": "Sherlock: the deduction"
    },
    "file": "B1_Green_Course_6B-10B/B1_10B-1_And_the_murderer_is.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_10B-1_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_10B-1_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_10B-1_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_10B_Photocopiables.pdf"
   },
   {
    "id": "10B-2",
    "unit": 10,
    "title": "And the murderer is…",
    "focus": "May and June (Ruth Rendell) • words from the story",
    "pages": "SB pp.102–103",
    "slides": 13,
    "skills": {
     "Vocabulary": "A short story by Ruth Rendell",
     "Listening": "Queens of Crime",
     "Games & songs": "Alibi!"
    },
    "file": "B1_Green_Course_6B-10B/B1_10B-2_And_the_murderer_is.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_10B-2_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_10B-2_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_10B-2_Teacher_answer_key.pdf",
    "pcm": "B1_Green_Course_6B-10B/B1_10B_Photocopiables.pdf"
   },
   {
    "id": "R9-10",
    "unit": 10,
    "title": "Revise and Check 9&10",
    "focus": "Files 9 & 10 review • 3rd conditional · quantifiers · relatives · tags",
    "pages": "SB pp.104–105",
    "slides": 12,
    "skills": {
     "Grammar": "Review of units 9–10",
     "Speaking": "Can you say this in English?",
     "Games & songs": "Board race"
    },
    "file": "B1_Green_Course_6B-10B/B1_R9-10_Revise_and_Check_9_10.pptx",
    "hw": "B1_Green_Course_6B-10B/B1_R9-10_Homework_sheet.pdf",
    "easy": "B1_Green_Course_6B-10B/B1_R9-10_Homework_sheet_easier.pdf",
    "key": "B1_Green_Course_6B-10B/B1_R9-10_Teacher_answer_key.pdf"
   }
  ],
  "CHEF": [
   {
    "id": "L1",
    "unit": 1,
    "title": "Welcome to the kitchen",
    "focus": "the kitchen team • the verb be + questions • your first day",
    "pages": "",
    "slides": 11,
    "file": "Kitchen_English_Chefs/Chef_L01_Welcome_to_the_kitchen.pptx",
    "hw": "Kitchen_English_Chefs/Chef_L01_Homework_sheet.pdf",
    "key": "Kitchen_English_Chefs/Chef_L01_Teacher_answer_key.pdf",
    "skills": {
     "Grammar": "the verb be + questions",
     "Vocabulary": "the kitchen team",
     "Speaking": "Two truths and a lie"
    }
   },
   {
    "id": "L2",
    "unit": 2,
    "title": "Kitchen equipment",
    "focus": "equipment • there is / there are · this / these • where is it?",
    "pages": "",
    "slides": 10,
    "file": "Kitchen_English_Chefs/Chef_L02_Kitchen_equipment.pptx",
    "hw": "Kitchen_English_Chefs/Chef_L02_Homework_sheet.pdf",
    "key": "Kitchen_English_Chefs/Chef_L02_Teacher_answer_key.pdf",
    "skills": {
     "Grammar": "there is / there are · this / these",
     "Vocabulary": "equipment",
     "Speaking": "Describe it, I'll draw it",
     "Games & songs": "Pass me the…, Chef!"
    }
   },
   {
    "id": "L3",
    "unit": 3,
    "title": "Ingredients",
    "focus": "food and ingredients • countable / uncountable · some / any • the delivery",
    "pages": "",
    "slides": 11,
    "file": "Kitchen_English_Chefs/Chef_L03_Ingredients_and_stock.pptx",
    "hw": "Kitchen_English_Chefs/Chef_L03_Homework_sheet.pdf",
    "key": "Kitchen_English_Chefs/Chef_L03_Teacher_answer_key.pdf",
    "skills": {
     "Grammar": "countable / uncountable · some / any",
     "Vocabulary": "food and ingredients",
     "Speaking": "Food you love to hate",
     "Games & songs": "Mystery basket"
    }
   },
   {
    "id": "L4",
    "unit": 4,
    "title": "Kitchen commands",
    "focus": "cutting verbs • imperatives: do / don't / please • the prep list",
    "pages": "",
    "slides": 10,
    "file": "Kitchen_English_Chefs/Chef_L04_Kitchen_commands.pptx",
    "hw": "Kitchen_English_Chefs/Chef_L04_Homework_sheet.pdf",
    "key": "Kitchen_English_Chefs/Chef_L04_Teacher_answer_key.pdf",
    "skills": {
     "Grammar": "imperatives: do / don't / please",
     "Vocabulary": "cutting verbs",
     "Listening": "How to chop an onion",
     "Speaking": "The terrible commis",
     "Games & songs": "Chef says…"
    }
   },
   {
    "id": "L5",
    "unit": 5,
    "title": "Cooking methods",
    "focus": "cooking methods • first, then, finally · for / until • your signature dish",
    "pages": "",
    "slides": 10,
    "file": "Kitchen_English_Chefs/Chef_L05_Cooking_methods_and_recipes.pptx",
    "hw": "Kitchen_English_Chefs/Chef_L05_Homework_sheet.pdf",
    "key": "Kitchen_English_Chefs/Chef_L05_Teacher_answer_key.pdf",
    "skills": {
     "Grammar": "first, then, finally · for / until",
     "Vocabulary": "cooking methods",
     "Reading": "Simple tomato sauce",
     "Listening": "Is this an Italian sauce?",
     "Speaking": "The best way… and the WORST way"
    }
   },
   {
    "id": "L6",
    "unit": 6,
    "title": "Numbers & time",
    "focus": "weights, temperatures, times • can / can't / could • How long? How much?",
    "pages": "",
    "slides": 10,
    "file": "Kitchen_English_Chefs/Chef_L06_Numbers_quantities_time.pptx",
    "hw": "Kitchen_English_Chefs/Chef_L06_Homework_sheet.pdf",
    "key": "Kitchen_English_Chefs/Chef_L06_Teacher_answer_key.pdf",
    "skills": {
     "Grammar": "can / can't / could",
     "Vocabulary": "weights, temperatures, times",
     "Speaking": "How long? What temperature?",
     "Games & songs": "Kitchen bingo"
    }
   },
   {
    "id": "L7",
    "unit": 7,
    "title": "Health & safety",
    "focus": "hazards and hygiene • must / mustn't / have to • the kitchen inspector",
    "pages": "",
    "slides": 10,
    "file": "Kitchen_English_Chefs/Chef_L07_Health_safety_hygiene.pptx",
    "hw": "Kitchen_English_Chefs/Chef_L07_Homework_sheet.pdf",
    "key": "Kitchen_English_Chefs/Chef_L07_Teacher_answer_key.pdf",
    "skills": {
     "Grammar": "must / mustn't / have to",
     "Vocabulary": "hazards and hygiene",
     "Reading": "The 4 Cs of food safety",
     "Speaking": "Agree or no way?",
     "Writing": "The worst kitchen in the world",
     "Games & songs": "The kitchen inspector"
    }
   },
   {
    "id": "L8",
    "unit": 8,
    "title": "Allergens & diets",
    "focus": "the 14 allergens · diets • Does it contain…? Is it…? • chef and waiter",
    "pages": "",
    "slides": 10,
    "file": "Kitchen_English_Chefs/Chef_L08_Allergens_and_dietary_needs.pptx",
    "hw": "Kitchen_English_Chefs/Chef_L08_Homework_sheet.pdf",
    "key": "Kitchen_English_Chefs/Chef_L08_Teacher_answer_key.pdf",
    "skills": {
     "Grammar": "Does it contain…? Is it…?",
     "Vocabulary": "the 14 allergens · diets",
     "Speaking": "The waiter asks…",
     "Games & songs": "Allergen detective"
    }
   },
   {
    "id": "L9",
    "unit": 9,
    "title": "Service!",
    "focus": "calls on the pass • present continuous • a busy service",
    "pages": "",
    "slides": 9,
    "file": "Kitchen_English_Chefs/Chef_L09_Service.pptx",
    "hw": "Kitchen_English_Chefs/Chef_L09_Homework_sheet.pdf",
    "key": "Kitchen_English_Chefs/Chef_L09_Teacher_answer_key.pdf",
    "skills": {
     "Grammar": "present continuous",
     "Vocabulary": "calls on the pass",
     "Speaking": "Chef v waiter",
     "Games & songs": "Service simulation"
    }
   },
   {
    "id": "L10",
    "unit": 10,
    "title": "The final shift",
    "focus": "past simple · what went wrong? • asking for help • the whole course",
    "pages": "",
    "slides": 10,
    "file": "Kitchen_English_Chefs/Chef_L10_Problems_and_final_shift.pptx",
    "hw": "Kitchen_English_Chefs/Chef_L10_Homework_sheet.pdf",
    "key": "Kitchen_English_Chefs/Chef_L10_Teacher_answer_key.pdf",
    "skills": {
     "Grammar": "past simple · what went wrong?",
     "Speaking": "My worst shift ever"
    }
   }
  ]
 },
 "extras": {
  "EF-B1": [
   {
    "label": "📗 Workbook answer key 1A–5B",
    "file": "B1_Green_Course_6B-10B/B1_Workbook_1A-5B_Teacher_answer_key.pdf"
   },
   {
    "label": "📗 Workbook answer key 6A–10B",
    "file": "B1_Green_Course_6B-10B/B1_Workbook_6A-10B_Teacher_answer_key.pdf"
   },
   {
    "label": "🧾 Photocopiables: teacher notes and answers",
    "file": "B1_Green_Course_6B-10B/B1_Photocopiables_Teacher_notes_and_answers.pdf"
   }
  ]
 }
};
